<section class="content">
    <section class="widget">
        <header>
            <span class="icon">&#128196;</span>
            <hgroup>
                <h1>Configurações</h1>
                <h2>Editar configurações de administrador</h2>
            </hgroup>
        </header>

        <div class="content">
            <form name="adminform" action="" method="post" enctype="multipart/form-data" _lpchecked="1">

                <div class="field-wrap">
                    <label>Importar Planilha do Hotmart:</label>
                    <input type="file" name="planilha">
                    <button type="submit" class="green" name="enviarPlanilha" />Enviar</button>
                </div>
            </form>
        </div>
</section>