<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script src="<?=HOMEP;?>assets/admin/js/jquery.wysiwyg.js"></script>
<script src="<?=HOMEP;?>assets/admin/js/custom.js"></script>
<script src="<?=HOMEP;?>assets/admin/js/cycle.js"></script>
<script src="<?=HOMEP;?>assets/admin/js/jquery.checkbox.min.js"></script>
<script src="<?=HOMEP;?>assets/admin/js/flot.js"></script>
<script src="<?=HOMEP;?>assets/admin/js/flot.resize.js"></script>
<script src="<?=HOMEP;?>assets/admin/js/flot-time.js"></script>
<script src="<?=HOMEP;?>assets/admin/js/flot-pie.js"></script>
<script src="<?=HOMEP;?>assets/admin/js/flot-graphs.js"></script>
<script src="<?=HOMEP;?>assets/admin/js/cycle.js"></script>
<script src="<?=HOMEP;?>assets/admin/js/jquery.tablesorter.min.js"></script>
<script type="text/javascript">
    // Feature slider for graphs
    $('.cycle').cycle({
        fx: "scrollHorz",
        timeout: 0,
        slideResize: 0,
        prev:    '.left-btn',
        next:    '.right-btn'
    });
</script>
</body>
</html>