<!DOCTYPE html>
<html lang="">
<head>
    <meta charset="utf-8">
    <title>#FADEV - Dashboard</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="robots" content="" />
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" href="<?=HOMEP;?>assets/admin/css/style.css" media="all" />
    <!--[if IE]><link rel="stylesheet" href="<?=HOMEP;?>assets/admin/css/ie.css" media="all" /><![endif]-->
    <!--[if IE 9]><link rel="stylesheet" href="<?=HOMEP;?>assets/admin/css/ie9.css" media="all" /><![endif]-->
    <!--[if lt IE 9]><link rel="stylesheet" href="<?=HOMEP;?>assets/admin/css/lt-ie-9.css" media="all" /><![endif]-->
</head>
<body>
<div class="testing">
    <header class="main">
        <h1><strong>#FADEV</strong> Dashboard</h1>
        <input type="text" value="Pesquisar" />
    </header>
    <section class="user">
        <div class="profile-img">
            <?php
            $users = $this->view->usuarios;
            foreach($users as $user);

            ?>
            <p><img src="<?=HOMEP;?>assets/admin/images/uiface2.png" alt="" height="40" width="40" /> Bem-vindo  <?php echo $user['email'];?> </p>
        </div>
        <div class="buttons">
            <button class="ico-font">&#59157;</button>
		<span class="button dropdown">
			<a href="#">Notificações <span class="pip">4</span></a>
			<ul class="notice">
                <li>
                    <hgroup>
                        <h1>You have a new task</h1>
                        <h2>Report web statistics week by week.</h2>
                    </hgroup>
                    <p><span>14:24</span></p>
                </li>
                <li>
                    <hgroup>
                        <h1>New comment</h1>
                        <h2>Comment on <em>About page</em> by Darren.</h2>
                    </hgroup>
                    <p><span>11:04</span></p>
                </li>
                <li>
                    <hgroup>
                        <h1>Broken link</h1>
                        <h2>We've spotted a broken link on the <em>Blog page</em>.</h2>
                    </hgroup>
                    <p><span>10:46</span></p>
                </li>
                <li>
                    <hgroup>
                        <h1>User report</h1>
                        <h2><em>Lee Grant</em> has been promoted to admin.</h2>
                    </hgroup>
                    <p><span>09:57</span></p>
                </li>
            </ul>
		</span> 
		<span class="button dropdown">
			<a href="#">Inbox <span class="pip">6</span></a>
			<ul class="notice">
                <li>
                    <hgroup>
                        <h1>Hi, I need a favour</h1>
                        <h2>John Doe</h2>
                        <h3>Lorem ipsum dolor sit amet, consectetuer sed aidping putamus delo de sit felume...</h3>
                    </hgroup>
                    <p><span>11:24</span></p>
                </li>
                <li>
                    <hgroup>
                        <h1><span class="icon">&#59154;</span>Hi, I need a favour</h1>
                        <h2>John Doe</h2>
                        <h3>Lorem ipsum dolor sit amet, consectetuer sed aidping putamus delo de sit felume...</h3>
                    </hgroup>
                    <p><span>11:24</span></p>
                </li>
                <li>
                    <hgroup>
                        <h1><span class="icon">&#59154;</span>Hi, I need a favour</h1>
                        <h2>John Doe</h2>
                        <h3>Lorem ipsum dolor sit amet, consectetuer sed aidping putamus delo de sit felume...</h3>
                    </hgroup>
                    <p><span>11:24</span></p>
                </li>
            </ul>
		</span>
            <span class="button">Live</span>
            <span class="button">Help</span>
            <span class="button blue"><a href="/admin/logout">Logout</a></span>
        </div>
    </section>
</div>

