<!DOCTYPE html>
<html lang="">
<head>
    <meta charset="utf-8">
    <title>MBR - Dashboard</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="robots" content="" />
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" href="<?=HOMEP;?>assets/admin/css/style.css" media="all" />
    <!--[if IE]><link rel="stylesheet" href="<?=HOMEP;?>assets/admin/css/ie.css" media="all" /><![endif]-->
    <!--[if IE 9]><link rel="stylesheet" href="<?=HOMEP;?>assets/admin/css/ie9.css" media="all" /><![endif]-->
    <!--[if lt IE 9]><link rel="stylesheet" href="<?=HOMEP;?>assets/admin/css/lt-ie-9.css" media="all" /><![endif]-->
</head>
<body>
<div class="testing">
    <header class="main">
        <h1><strong>MBR</strong> Dashboard</h1>
        <!--<input type="text" value="Pesquisar" />-->
    </header>
    <section class="user">
        <div class="profile-img">
            <?php
            $users = $this->view->usuarios;
                foreach($users as $user);
            ?>
            <p><img src="<?=HOMEP;?>assets/admin/images/uiface2.png" alt="" height="40" width="40" /> Bem-vindo  <?php echo $user['email'];?> </p>
        </div>
        <div class="buttons">
            <button class="ico-font">&#59157;</button>
            <a href="<?php echo BASE;?>" target="_blank"><span class="button green">Ver site</span></a>
            <a href="/admin/logout"><span class="button blue">Logout</span></a>
        </div>
    </section>
</div>

