<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <title>#FADEV - Painel Administrativo</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="robots" content="" />
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" href="<?=HOMEP;?>assets/admin/css/style.css" media="all" />
    <!--[if IE]><link rel="stylesheet" href="<?=HOMEP;?>assets/admin/css/ie.css" media="all" /><![endif]-->
    <!--[if IE 9]><link rel="stylesheet" href="<?=HOMEP;?>assets/admin/css/ie9.css" media="all" /><![endif]-->
    <!--[if lt IE 9]><link rel="stylesheet" href="<?=HOMEP;?>assets/admin/css/lt-ie-9.css" media="all" /><![endif]-->
</head>
<body class="login">
<section>
    <h1><strong>#FADEV</strong> Admin</h1>
    <form method="post" action="/admin/dashboard">
        <input type="text" name="email" value="E-mail" />
        <input value="Senha" name="senha" type="password" />
        <button type="submit" name="login" class="blue">Login</button>
    </form>
    <p><a href="#">Esqueceu a senha?</a></p>
</section>
<script src="<?=HOMEP;?>assets/js/jquery-1.11.1.min.js"></script>
<script type="text/javascript">
    // Page load delay by Curtis Henson - http://curtishenson.com/articles/quick-tip-delay-page-loading-with-jquery/
    $(function(){
        $('.login button').click(function(e){
            // Get the url of the link
            var toLoad = $(this).attr('href');

            // Do some stuff
            $(this).addClass("loading");

            // Stop doing stuff
            // Wait 700ms before loading the url
            setTimeout(function(){window.location = toLoad}, 10000);

            // Don't let the link do its natural thing
            e.preventDefault
        });

        $('input').each(function() {

            var default_value = this.value;

            $(this).focus(function(){
                if(this.value == default_value) {
                    this.value = '';
                }
            });

            $(this).blur(function(){
                if(this.value == '') {
                    this.value = default_value;
                }
            });

        });
    });
</script>
</body>
</html>