<nav>
    <ul>
        <li class="section"><a href="<?=HOMEP;?>admin/dashboard"><span class="icon">&#59176;</span> Dashboard</a></li>
        <li>
            <a href="pages-table.html"><span class="icon">&#128196;</span> Pages</a>
            <ul class="submenu">
                <li><a href="page-new.html">Create page</a></li>
                <li><a href="page-timeline.html">View pages</a></li>
            </ul>
        </li>
        <li>
            <a href="files.html"><span class="icon">&#127748;</span> Media <span class="pip">7</span></a>
            <ul class="submenu">
                <li><a href="files-upload.html">Upload file</a></li>
                <li><a href="files.html">View files</a></li>
            </ul>
        </li>
        <li>
            <a href="blog-timeline.html"><span class="icon">&#59160;</span> Blog <span class="pip">12</span></a>
            <ul class="submenu">
                <li><a href="blog-new.html">New post</a></li>
                <li><a href="blog-table.html">All posts</a></li>
                <li><a href="comments-timeline.html">View comments</a></li>
            </ul>
        </li>
        <li><a href="statistics.html"><span class="icon">&#128202;</span> Statistics</a></li>
        <li><a href="users.html"><span class="icon">&#128101;</span> Users <span class="pip">3</span></a></li>
        <li>
            <a href="ui-elements.html"><span class="icon">&#9881;</span> UI Elements</a>
            <ul class="submenu">
                <li><a href="icon-fonts.html">Icon fonts</a></li>
            </ul>
        </li>
    </ul>
</nav>