<nav>
    <ul>
        <li class="section"><a href="<?=HOMEP;?>admin/dashboard"><span class="icon">&#59176;</span> Dashboard</a></li>
        <li>
            <a href="/admin/registros"><span class="icon">&#128196;</span> Registros</a>
        </li>

        <li>
            <a href="<?=HOMEP;?>admin/users"><span class="icon">&#128101;</span> Usuários
            </a>
            <ul class="submenu">
                <li><a href="/admin/profile">Perfil</a></li>
            </ul>
        </li>

    </ul>
</nav>