

<div id="page-title">

    <div class="title-bar dark bg-black padded-vertical-70">
        <div class="bg-image bg-image-3"></div>
        <div class="overlay overlay-black editable-alpha" data-alpha="80"></div>
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <span class="icon icon-lg icon-circle icon-primary margin-bottom-20"><i class="fa fa-times"></i></span>
                    <h1 class="text-uppercase margin-bottom-0">Erro! <strong>404</strong> </h1>
                    <span class="sep sep-primary"></span>
                    <div class="font-alt text-muted margin-bottom-20">Ooops... <?php echo utf8_encode('Não conseguimos identificar o que procura');?> :-(</div>
                    <a href="#" class="btn btn-sm btn-primary">Home</a> <a href="#" class="btn btn-sm btn-default">Contate-nos</a>
                </div>
            </div>
        </div>
    </div>

</div>

