<footer>
    <div class="container">
        <div class="container-fluidr">
            <div class="col-md-6 col-sm-6 footerleft ri hri">
                <br><p>Telefone: (61) 98354-9444</p>
                <p>suporte@mulheresbemresolvidas.com.br</p>
                <p>SHN Quadra 01, Ed. Le Quartier Bloco A, Sala 1514</p>
                <p>CNPJ: 23.705.563.0001/80</p>
            </div>

            <div class="col-md-6 col-sm-6 footerleft paddingtop-bottom ri men">
                <p><img src="<?php echo BASE;?>images/logo-footer.png" width="150"></p>
            </div>
        </div>
    </div>
</footer>
<!--footer start from here-->
<div class="copyright">
    <div class="container">
        <div class="col-md-6">
            <p>© 2013 - 2017 - Todos os direitos reservados</p>
        </div>
        <div class="col-md-6">
            <p class="pull-right direitos"><a href="http://lp.toquefeminino.com.br/politicas-de-privacidade/?_ga=1.185137449.101979915.1492458710" class="html5lightbox" target="_blank">Política de privacidade</a> | <a href="http://lp.toquefeminino.com.br/termos-de-uso/?_ga=1.185137449.101979915.1492458710" class="html5lightbox" target="_blank">Termos de uso</a></p>
        </div>
    </div>
</div>

<script src="<?php echo BASE;?>/assets/js/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo BASE;?>/assets/html5lightbox/html5lightbox.js"></script>
<script src="<?php echo BASE;?>/assets/js/bootstrap.min.js"></script>
<script src="<?php echo BASE;?>/assets/js/scripts.js"></script>

</body>
</html>