
<!-- Footer -->
<footer id="footer" class="bg-black dark">

    <div class="container padded-vertical-40">
        <div class="row">
            <div class="col-md-2 col-sm-6">
                <h5 class="text-light"><strong><?php echo utf8_encode('Navegação');?></strong></h5>
                <!-- Navigation list -->
                <ul class="list-navigation margin-bottom-20">
                    <li><a href="#">Home Page</a></li>
                    <li><a href="#">Features</a></li>
                    <li><a href="#">Templates</a></li>
                    <li><a href="#">Elements</a></li>
                    <li><a href="#">Documentation</a></li>
                    <li><a href="#">Buy it!</a></li>
                </ul>
            </div>
            <div class="col-md-4 col-sm-6">
                <h5 class="text-light">Diga um <strong>Oi!</strong>!</h5>
                <!-- Contact Form -->
                <form id="contact-form" class="margin-bottom-20">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" id="name" name="name" placeholder="Nome">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" id="message" name="message" rows="3"  placeholder="Mensagem"></textarea>
                    </div>
                    <div class="form-group clearfix">
                        <button type="submit" class="btn btn-primary btn-filled btn-sm pull-right">Enviar!</button>
                    </div>
                </form>
            </div>
            <div class="col-md-4 col-sm-6">
                <h5 class="text-light"><strong>Contate</strong>-nos</h5>
                <!-- List with Icons -->
                <ul class="list-unstyled list-unstyled-icons margin-bototm-20">
                    <li><i class="text-muted inline-icon fa fa-map-marker"></i><strong><?php echo utf8_encode('Endereço')?>:</strong> <span class="text-muted">SQN 316 Bloco F. 307 Asa Norte - Brasilia/DF</span></li>
                    <li><i class="text-muted inline-icon fa fa-comment"></i><strong>E-mail:</strong> <span class="text-muted"><a href="#">contato@fadev.com.br</a></span></li>
                    <li><i class="text-muted inline-icon fa fa-phone"></i><strong>Cel. e Whatsapp:</strong> <span class="text-muted">(61)98314-7515</span></li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-6">
                <h5 class="text-light"><strong><?php echo utf8_encode('Mídias')?></strong> Sociais</h5>
                <!-- Social Icons -->
                <div class="margin-bototm-20">
                    <a href="https://www.facebook.com/LudsonAlmeidaDesenvolvedor/" target="_blank" class="icon icon-circle icon-filled icon-xs icon-facebook"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="icon icon-circle icon-filled icon-xs icon-twitter"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="icon icon-circle icon-filled icon-xs icon-google-plus"><i class="fa fa-google-plus"></i></a>
                    <a href="#" class="icon icon-circle icon-filled icon-xs icon-youtube"><i class="fa fa-youtube"></i></a>
                </div>
            </div>
        </div>
    </div>

    <!-- Copyright -->
    <div class="copyright bordered-top">
        <div class="container padded-vertical-30">
            <span class="text-muted">Copyright <strong><?php echo utf8_encode('Fábrica de Desenvolvedores'); ?> / Ludson Almeida</strong> 2017&copy;</span>
            <ul class="list-inline pull-right text-muted margin-bottom-0">
                <li><a href="#">Home</a></li>
                <li><a href="#"><?php echo utf8_encode('Documentação');?></a></li>
                <li><a href="#"><?php echo utf8_encode('Conteúdos!');?></a></li>
            </ul>
        </div>
    </div>

</footer>
<!-- Footer / End -->

<!-- Alert Modal -->
<div class="modal fade" id="alertModal" tabindex="-1" role="dialog" aria-labelledby="alertModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title text-center" id="alertModalLabel"></h4>
            </div>
            <div class="modal-body text-center">
                <div class="modal-alert-content margin-bottom-20"></div>
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal"><i class="icon-before fa fa-times"></i>Fechar</button>
            </div>
        </div>
    </div>
</div>
<!-- Alert Modal / End -->

<!-- Rules Modal -->
<div class="modal fade" id="rulesModal" tabindex="-1" role="dialog" aria-labelledby="rulesModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="rulesModalLabel"><?php echo utf8_encode('Fábrica de Desenvolvedores - Ludson Almeida </h4>
            </div>
            <div class="modal-body">
                <ol>
                    <li>Você recebera <strong>emails</strong> com conteúdos gratuitos como: artigos, video-aulas etc..</li>
                    <li>Seu endereço de e-mail <strong>não será usado para nenhum outro propósito</strong> a não ser o específicado acima.</li>
                </ol>
                <p class="margin-bottom-0">Em acordo, basta clicar no botão <strong>"Baixar Agora"</strong>.</p>');?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>
<!-- Rules Modal / End -->

<!-- Page Curtain -->
<div id="page-curtain" class="curtain-white"></div>

<!-- Scripts -->
<script type="text/javascript" src="<?=HOME?>assets/js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/page-loader.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/jquery.appear.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/owl.carousel.min.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/jquery.counterup.min.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/jquery.colorbox-min.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/waypoints.min.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/jquery.localscroll-1.2.7-min.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/jquery.scrollTo-1.4.3.1-min.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/jquery.tweet.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/jquery.parallax.min.js"></script>
<script type="text/javascript" src="<?=HOME?>assets/js/jquery.fitvids.js"></script>

<!-- Custom Script -->
<script type="text/javascript" src="<?=HOME?>assets/js/custom.js"></script>


<script>
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-XXXXX-X']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
</script>


</body>

</html>

