<!DOCTYPE html>
<html lang="pt-br">
<head>

    <!-- Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="utf-8" />
    <!-- Title -->
    <title>Fábrica de Desenvolvedores - Ludson Almeida</title>

    <!-- Favicons -->
    <link rel="shortcut icon" href=<?=HOME?>assets/images/favicon.png">
    <link rel="apple-touch-icon" href="<?=HOME?>assets/images/favicon_60x60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="<?=HOME?>assets/images/favicon_76x76.png">
    <link rel="apple-touch-icon" sizes="120x120" href="<?=HOME?>assets/images/favicon_120x120.png">
    <link rel="apple-touch-icon" sizes="152x152" href="<?=HOME?>assets/images/favicon_152x152.png">

    <!-- Google Web Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,500,700' rel='stylesheet' type='text/css'>

    <!-- Stylesheets -->
    <link rel="stylesheet" type="text/css" href="<?=HOME?>assets/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="<?=HOME?>assets/css/style.css" />
    <link rel="stylesheet" type="text/css" href="<?=HOME?>assets/css/animations.css" />
    <link rel="stylesheet" type="text/css" href="<?=HOME?>assets/css/owl.carousel.css" />
    <link rel="stylesheet" type="text/css" href="<?=HOME?>assets/css/owl.transitions.css" />
    <link rel="stylesheet" type="text/css" href="<?=HOME?>assets/css/owl.theme.css" />
    <link rel="stylesheet" type="text/css" href="<?=HOME?>assets/colors/red.css" id="colors" />
    <link rel="stylesheet" type="text/css" href="<?=HOME?>assets/css/font-awesome.min.css" />

</head>
<body class="sticky-nav">

<!-- Loader -->
<div id="page-loader" class="loader-white"></div>

<!-- Header -->
<header id="header" class="header header-white wide clearfix">

    <div class="row">
        <div class="col-xs-12">
        <?php include_once('menu.phtml');?>
        </div>
    </div>
    <div class="mobile-menu text-uppercase"></div>

</header>
<!-- Header / End -->
