    <div class="container-fluid black">
        <div class="container">
            <ul>
                <li><a href="#"><img src="assets/images/gazeta.png"></a></li>
                <li><a href="#"><img src="assets/images/band.png"></a></li>
                <li><a href="#"><img src="assets/images/bolsa.png"></a></li>
                <li><a href="#"><img src="assets/images/catraca-livre.png"></a></li>
                <li><a href="#"><img src="assets/images/terra.png"></a></li>
                <li><a href="#"><img src="assets/images/globo.png"></a></li>
            </ul>
        </div>
    </div>

    <div class="container">
        <div class="col-md-12 text-center titulo1">
            <h1 class="t1 col-md-12">Você sabia?</h1>
            <hr class="bar" />
            <div class="sabia">

                <div class="col-md-3">
                    <div class="circle-tile ">
                        <div class="circle-tile-heading dark-b"><p class="value">98<span>%</span></p></div>
                        <div class="circle-tile-content um">
                            <div class="circle-tile-description text-faded">das mulheres</div>
                            <div class="circle-tile-number text-faded">Não se acham bonitas</div>

                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="circle-tile ">
                        <div class="circle-tile-heading dark-b"><p class="value">40<span>%</span></p></div>
                        <div class="circle-tile-content dois">
                            <div class="circle-tile-description text-faded">das mulheres</div>
                            <div class="circle-tile-number text-faded">Nunca se tocaram</div>

                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="circle-tile ">
                        <div class="circle-tile-heading dark-b"><p class="value">78<span>%</span></p></div>
                        <div class="circle-tile-content tres">
                            <div class="circle-tile-description text-faded" style="margin-top:-5px !important;">das mulheres</div>
                            <div class="circle-tile-number text-faded">Não chegam ou tem dificuldade de chegar lá</div>

                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="circle-tile">
                        <div class="circle-tile-heading dark-b"><p class="value">58<span>%</span></p></div>
                        <div class="circle-tile-content quatro">
                            <div class="circle-tile-description text-faded" style="margin-top:-10px !important;">das mulheres</div>
                            <div class="circle-tile-number text-faded">Acima dos 40 anos sofrem de incontinências urinárias </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="circle-tile">
                        <div class="circle-tile-heading dark-b"><p class="value">33<span>%</span></p></div>
                        <div class="circle-tile-content cinco">
                            <div class="circle-tile-description text-faded">das mulheres</div>
                            <div class="circle-tile-number text-faded">Não sentem desejo</div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="circle-tile">
                        <div class="circle-tile-heading dark-b"><p class="value">21<span>%</span></p></div>
                        <div class="circle-tile-content seis">
                            <div class="circle-tile-description text-faded">das mulheres</div>
                            <div class="circle-tile-number text-faded">Tem dificuldade em relação a lubrificação</div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="circle-tile">
                        <div class="circle-tile-heading dark-b"><p class="value">65<span>%</span></p></div>
                        <div class="circle-tile-content sete">
                            <div class="circle-tile-description text-faded">das mulheres</div>
                            <div class="circle-tile-number text-faded">Reclamam de baixo desejo</div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="circle-tile">
                        <div class="circle-tile-heading dark-b"><p class="value">75<span>%</span></p></div>
                        <div class="circle-tile-content oito">
                            <div class="circle-tile-description text-faded">das mulheres</div>
                            <div class="circle-tile-number text-faded">Reclamam de cólica menstrual</div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="container-fluid text-center titulo2">
        <h1 class="t1 col-md-12">O que é Ginástica Íntima?</h1>
        <hr class="bar" />
        <p class="text-center">Técnica de exercícios para o fortalecimento<br>
            da musculatura vaginal que traz diversos benefícios para a mulher</p>

        <div class="center-block info"><img src="assets/images/pompo-info.png" class="img-responsive"></div>

        <div class="container desc">
            <div class="col-md-4">

                <h1 class="h1">PRÁTICA</h1>
                <p>Os exercícios fortalecem
                    a musculatura e
                    aumentam a irrigação
                    sanguinea na região íntima</p>
            </div>
            <div class="col-md-4">
                <h1 class="h1">BENEFÍCIO</h1>
                <p>Aumenta a consistência
                    corporal e regula
                    toda a saúde
                    íntima da mulher</p>
            </div>
            <div class="col-md-4">
                <h1 class="h1">RESULTADO</h1>
                <p>Proporciona mais prazer
                    e aumenta a confiança
                    da mulher em relaçao
                    ao seu desempenho
                    sexual</p>
            </div>
        </div>
    </div>

    <div class="container-fluid text-center titulo3">
        <h1 class="t1 col-md-12">Conhecendo a Musculatura</h1>
        <hr class="bar" />
        <div class="center-block info"><img src="assets/images/musculatura.png" class="img-responsive"></div>

        <p>A contração da musculatura do Assoalho Pelvico - MAP  pode ser<br>
            facilmente percebida internamente à vagina, logo na entrada e a<br>
            alguns centímetros de profundidade. É ela a responsável pela<br>
            sensação de pressão percebida durante a penetração e todo ato sexual</p>

    </div>

    <div class="container-fluid text-center titulo4">
        <h1 class="t4 col-md-12">Recomendado pelos médicos</h1>
        <hr class="bar2" />
        <p class="text-center">O pompoarismo é recomendado por médicos<br> ginecologistas, fisioterapeutas e até mesmo psicólogos<br>  como um exercício fundamental para toda mulher</p>
        <div class="center-block info"><div class="info2"></div><img src="assets/images/beneficios-ci.png" class="img-responsive"></div>

        <div class="center-block bt"><a href="#contato" class="anchorLink"><button class="button btn btn-success btn-large col-md-4">Como participar</button></a></div>
    </div>


    <div class="container-fluid text-center titulo5">
        <h1 class="t1 col-md-12">Por que toda mulher<br>
            deve praticar Ginastica Íntima?</h1>
        <hr class="bar" />
        <p class="text-center">Diga-me o que acontece quando você não exercita um<br> músculo? Naturalmente, se você nunca exercita um músculo,<br> a tendência é que esse músculo fique flácido. A região íntima<br> é composta por estruturas musculares, e se você nunca<br> exercitou esses músculos, a tendência é que essa musculatura<br> fique enfraquecida e flácida.</p>


        <h1 style="margin-top:60px;" class="t1 col-md-12">Por que isso atrapalha<br>
            significativamente<br>
            a qualidade das suas relações?</h1>
        <hr class="bar" />
        <p class="text-center">Primeiro, porque quando a vagina está mais flácida, a<br> sensação da penetração  é menos intensa, tanto para o<br> homem, que consegue perceber essa frouxidão, quanto para a<br> mulher.

            Outros sintomas comuns são o ressecamento, dores na<br> relação e dificuldade de chegar lá, afinal quem é que vai<br> atingir o lá se não consegue sentir o parceiro?</p>
    </div>

    <div class="container-fluid text-center titulo6">
        <h1 class="t1 col-md-12">Benefícios da <br>
            Ginastica Íntima</h1>
        <hr class="bar" />

        <div class="container">
            <ul>
                <li>
                    <img src="assets/images/icone-inc-1.png" /><p>Trata e previne
                        a incontinência urinária</p></li>

                <li>
                    <img src="assets/images/icone-inc-2.png" /><p>Trata e previne
                        a queda da bexiga</p></li>

                <li>
                    <img src="assets/images/icone-inc-3.png" /><p>Restabelece
                        o tônus vaginal</p></li>

                <li>
                    <img src="assets/images/icone-inc-4.png" /><p>Trate dores no sexo
                        e dificuldade de penetração</p></li>

                <li>
                    <img src="assets/images/icone-inc-5.png" />
                    <p>Facilita o parto
                        normal</p></li>
                <li>
                    <img src="assets/images/icone-inc-6.png" />
                    <p>Facilita a
                        gravidez</p></li>

                <li>
                    <img src="assets/images/icone-inc-7.png" />
                    <p>Regula o ciclo
                        o fluxo menstrual</p></li>

                <li>
                    <img src="assets/images/icone-inc-8.png" />
                    <p>Regula
                        a lubrificação vaginal</p></li>

                <li>
                    <img src="assets/images/icone-inc-9.png" />
                    <p>Aumenta a
                        sensibilidade genital</p></li>

                <li>
                    <img src="assets/images/icone-icon-10.png" />
                    <p>Ajuda a alcançar
                        ou intensificar o orgasmo</p></li>

                <li>
                    <img src="assets/images/icone-inc-11.png" />
                    <p>Ajuda a controlar
                        a ejaculação do parceiro</p></li>

                <li>
                    <img src="assets/images/icone-inc-12.png" />
                    <p>Trata e previne cólicas menstruais e TPM</p></li>

                <li>
                    <img src="assets/images/icone-inc-13.png" />
                    <p>Apimenta
                        a relação</p></li>
                <li>
                    <img src="assets/images/icone-inc-14.png" />
                    <p>Melhora a autoestima</p></li>

                <li>
                    <img src="assets/images/icone-inc-15.png" /><p>Clareia
                        a mucosa genital</p></li>
            </ul>

        </div>
    </div>


    <div class="container-fluid text-center titulo7">
        <h1 class="t1 col-md-12">O que as alunas dizem</h1>
        <hr class="bar" />
        <p class="text-center">alunas que gentilmente autorizaram<br> a publicação de suas imagens</p>

        <section id="carousel">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="quote"><i class="fa fa-quote-left fa-4x"></i></div>
                        <div class="carousel slide" id="fade-quote-carousel" data-ride="carousel" data-interval="3000">
                            <!-- Carousel indicators -->
                            <ol class="center-block carousel-indicators" style="margin-left:-40px;">
                                <li data-target="#fade-quote-carousel" data-slide-to="0" class="active"></li>
                                <li data-target="#fade-quote-carousel" data-slide-to="1"></li>
                                <li data-target="#fade-quote-carousel" data-slide-to="2"></li>
                                <li data-target="#fade-quote-carousel" data-slide-to="3"></li>
                            </ol>
                            <!-- Carousel items -->
                            <div class="carousel-inner">
                                <div class="active item">
                                    <div class="profile-circle" style=""><img src="assets/images/depoimento-1.png" class="img-responsive" /></div>
                                    <blockquote>
                                        <h4>Ana Paula</h4>
                                        <p>Meu maior benefício foi ter de volta minha libido, a lubrificação e autoestima, que havia perdido por conta desses problemas que realmente me incomodavam.</p>
                                    </blockquote>
                                </div>
                                <div class="item">
                                    <div class="profile-circle" style=""><img src="assets/images/depoimento-2.png" class="img-responsive" /></div>
                                    <blockquote>
                                        <h4>Denise Campina</h4>
                                        <p>Hoje não tenho mais problemas com a falta de lubrificação, nem as recorrentes crises de infecção urinária. A cada dia me sinto mais segura e mais feliz com os benefícios.</p>
                                    </blockquote>
                                </div>

                                <div class="item">
                                    <div class="profile-circle" style=""><img src="assets/images/depoimento-3.png" class="img-responsive" /></div>
                                    <blockquote>
                                        <h4>Emiliene Silva</h4>
                                        <p>O que me impressionou, e na minha opinião é o faz a diferença desse curso, é atenção que a Cátia e a sua equipe dão para as alunas, somos atendidas com um toque de delicadeza.</p>
                                    </blockquote>
                                </div>

                                <div class="item">
                                    <div class="profile-circle" style=""><img src="assets/images/depoimento-4.png" class="img-responsive" /></div>
                                    <blockquote>
                                        <h4>Paula Barros</h4>
                                        <p>Com apenas duas semanas praticando já notei resultados incríveis, olha que ainda não estou usando acessórios. Muito grata por tudo Cátia, está mudando minha vida.</p>
                                    </blockquote>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

    <div class="container-fluid text-center titulo8">
        <h1 class="t1 col-md-12">O que exatamente você<br>
            vai aprender nesse curso?</h1>
        <hr class="bar" />
        <img src="assets/images/learnicon.png" width="110" style="margin-top:50px;">

        <div class="container">
            <p class="desct8">
                O curso é composto por uma série de vídeos com aulas práticas, didáticas<br> e divertidas, para você aprender a <b>ginástica íntima</b> com um método<br> comprovadamente eficiente.
                <br><br>
                Hoje já são mais de <b>10 mil alunas</b> praticando a ginástica íntima com esse<br> método!
            </p>

            <div class="col-md-2"></div>
            <div class="col-md-10">
                <ul class="check">
                    <li>Identificando a musculatura</li>
                    <li>1ª semana de treino: sem acessórios</li>
                    <li>2ª semana de treino: sem acessórios</li>
                    <li>3ª semana de treino: sem acessórios</li>
                    <li>4ª semana de treino: sem acessórios</li>
                    <li>Higiene dos acessórios</li>
                    <li>Posições com o parceiro</li>
                    <li>Considerações finais</li>
                    <li>Tira dúvidas</li>
                    <li>Caderninho de exercícios</li>
                    <li>Apostila em PDF</li>

                </ul>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>

    <div class="container-fluid text-center titulo9">
        <h1 class="t1 col-md-12">Tipos de materiais</h1>
        <hr class="bar" />
        <p class="text-center">Será disponibilizado uma grande variedade de materiais<br> que facilitaram na metodologia do curso e te ajudaram a<br> chegar ao resultado esperado.</p>

        <div class="container" sty>
            <div class="col-md-4">
                <img src="assets/images/video-icon.png" width="120" />
                <p>videos</p>
            </div>

            <div class="col-md-4">
                <img src="assets/images/pdficon.png"  width="102" />
                <p>documentos</p>
            </div>

            <div class="col-md-4">
                <img src="assets/images/audioicon.png"  width="120" />
                <p>áudio</p>
            </div>
        </div>
    </div>

    <div class="container">

        <div class="text-center">
            <h3 style="color:#555">Veja outros relatos na comunidade exclusiva<br> para as alunas do curso no <b>facebook</b></h3>

            <a href="http://lp.toquefeminino.com.br/cpp1-00-comunidade/" class="html5lightbox" data-width=530 data-height=411>
                <button class="button btn btn-info btn-small html5lightbox face" style="">Clique para espiar</button>
            </a>
        </div>
    </div>

    <div class="container-fluid text-center titulo10">
        <h1 class="t1 col-md-12">Aulas sobre Ginástica Íntima</h1>
        <hr class="bar2" />

        <div class="container">
            <div class="col-md-4"><a href="https://www.youtube.com/watch?v=lseylxWq-P4" class="html5lightbox hvr-grow-shadow"><img src="assets/images/thumb1.jpg" class="img-responsive " width="370" height="210"/></a></div>
            <div class="col-md-4"><a href="https://www.youtube.com/watch?v=-nenORiMiCw" class="html5lightbox hvr-grow-shadow"><img src="assets/images/thumb2.jpg" class="img-responsive" width="370" height="210" /></a></div>
            <div class="col-md-4"><a href="https://www.youtube.com/watch?v=f6v8la6VEDM" class="html5lightbox hvr-grow-shadow"><img src="assets/images/thumb3.jpg" class="img-responsive" width="370" height="210" /></a></div>

            <div class="col-md-4"><a href="https://www.youtube.com/watch?v=xqWBO_AdOdw" class="html5lightbox hvr-grow-shadow"><img src="assets/images/thumb4.jpg" class="img-responsive" width="370" height="210" /></a></div>
            <div class="col-md-4"><a href="https://www.youtube.com/watch?v=BPMa2eIUDis" class="html5lightbox hvr-grow-shadow"><img src="assets/images/thumb5.jpg" class="img-responsive" width="370" height="210" /></a></div>
            <div class="col-md-4"><a href="https://www.youtube.com/watch?v=8qvmEYWLVMc" class="html5lightbox hvr-grow-shadow"><img src="assets/images/thumb6.jpg" class="img-responsive" width="370" height="210" /></a></div>
        </div>

    </div>

    <div class="container-fluid text-center titulo11">

        <h1 class="t1 col-md-12">Conheça a história de algumas alunas</h1>
        <hr class="bar" />
        <p class="text-center">Saiba o que algumas alunas dizem sobre o curso.</p>

        <div class="container">
            <div class="col-md-6"><a href="https://www.youtube.com/watch?v=pXRqym81rbk" class="html5lightbox"><img src="assets/images/thumb-yt.jpg" class="img-responsive"/></a></div>
            <div class="col-md-6"><a href="https://www.youtube.com/watch?v=JgL-w33sGTM" class="html5lightbox"><img src="assets/images/thumb-yt2.jpg" class="img-responsive"/></a></div>
        </div>
    </div>


    <div class="container-fluid text-center titulo11">

        <h1 class="t1 col-md-12">Quer receber o material<br>
            gratuito sobre Ginastica Íntima?</h1>
        <hr class="bar" />
        <p class="text-center">Faça o download do <b>livro digital</b></p>

        <div class="container">
            <div class="col-md-6"><img src="assets/images/ebookpp.png" class="img-responsive" /></div>
            <div class="col-md-6"><p>Gina?stica Íntima, e? uma te?cnica de<br> contrac?ão e relaxamento do canal que<br> proporciona va?rios benefi?cios para a<br> sau?de da mulher dentre outros aspectos.<br> A gina?stica i?ntima passou um bom tempo<br> rodeada por mitos e tabus, pore?m seus<br> benefi?cios foram comprovados ao longo<br> dos anos e hoje qualquer mulher pode<br> praticar.</p></div>
        </div>

        <a href="#optin" class="html5lightbox" data-width=630>
            <button class="button btn btn-alert btn-small ebook img-responsive">Quero receber o e-book</button>
        </a>

        <!-- OPTIN FORM -->
        <div class="optin col-md-4" id="optin" style="display:none">
            <h2>PREENCHA O FORMULÁRIO</h2>
            <form accept-charset="UTF-8" action="https://cr244.infusionsoft.com/app/form/process/d87d007b0f140de997023f3dceba9bc2" class="infusion-form" method="POST" style="padding:30px">

                <input name="inf_form_xid" type="hidden" value="d87d007b0f140de997023f3dceba9bc2">
                <input name="inf_form_name" type="hidden" value="eboook-aperta">
                <input name="infusionsoft_version" type="hidden" value="1.60.0.50">
                <input name="inf_custom_LeadSource" type="hidden" value="null">

                <div class="infusion-field">
                    <label for="inf_field_Email" style="display: none;">Email *</label>

                    <input class="infusion-field-input-container" id="inf_field_Email" name="inf_field_Email" type="text"
                           style="color: #555;
			    width: 100%;
			    border-radius: 0;
			    padding: 15px;
			    margin: 0 0 .8em;
			    box-sizing: border-box;
			    font-size: 17px;
			    background: #eee;
			    border: 0;
			    border: 1px solid transparent;
			    box-shadow: inset 0 2px 3px rgba(0,0,0,.1);
				"
                           placeholder="Digite seu e-mail"
                        ></div>

                <div class="infusion-submit">
                    <input type="submit"
                           style="
			        	margin-top: 20px;
					    margin-bottom: 40px;
					    height: 80px;
					    font-size: 22pt;
					    color: #fff;
					    border-radius: 15px;
					    background:#eb8613;" value="Quero receber o e-book">
                    <p class="privacy"
                       style="
					    text-align: center;
					    margin-top: .8em;
					    color: #444;
					    opacity: .5;
					    margin-top:-20px">Nós respeitamos sua privacidade</p>
                </div>

            </form>
            <script type="text/javascript" src="https://cr244.infusionsoft.com/app/webTracking/getTrackingCode"></script>
        </div>
        <!-- OPTIN FORM -->

    </div>


    <div class="container-fluid text-center titulo12">
        <h1 class="t1 col-md-12">Principais dúvidas<br> Perguntas e respostas</h1>
        <hr class="bar" />
        <p class="text-center">Segue abaixo algumas dúvidas recorrentes<br> que você pode vir a ter, assim você pode tirar<br> todas as dúvidas necessárias e seguir tranquila<br> na sua decisão.</b></p>


        <div class="container">
            <ul class="faq">
                <li>
                    <h3>Quais são as formas de pagamento?</h3>
                    <p>Você poderá realizar o pagamento de três formas: no seu cartão de crédito, sendo possível realizar o parcelamento em até 12 vezes, ou através de boleto bancário. Caso opte por boleto bancário, sua inscrição será efetivada somente após a compensação do boleto. Não é possível realizar o parcelamento do pagamento através de boleto bancário. Outra forma de pagamento é através do Paypal.</p>
                </li>

                <li>
                    <h3>Como funciona a garantia?</h3>
                    <p>Após o pagamento, você terá 30 dias para avaliar se o curso atinge suas expectativas. Se por qualquer motivo você queira o reembolso, basta enviar um e-mail  para <span style="font-size:11px;">suporte@mulheresbemresolvidas.com.br</span> , que será feito integralmente e sem questionamentos. Esta garantia existe para você não corra qualquer risco na hora de adquirir o seu curso. Tenho a certeza da qualidade do produto, mas também sabemos que imprevistos acontecem.</p>
                </li>

                <li>
                    <h3>As aulas são todas on-line?</h3>
                    <p>Sim, todas as aulas são online em vídeo com disponibilização de materiais de apoios como ebooks em pdf e audio mp3, não temos cursos presenciais. A partir do momento da efetivação do seu pagamento em nosso sistema, terá acesso imediato ao conteúdo integral de curso, os dados de acesso serão enviamos por e-mail a você.</p>
                </li>

                <li>
                    <h3>Onde receberei os dados para acessar ao curso?</h3>
                    <p>Após o pagamento, você receberá automaticamente em seu e-mail cadastrado os seus dados de acesso. É importante que você guarde este e-mail e, como sugestão, pode favoritar em seu navegador a página de acesso ao treinamento. Caso não encontre este e-mail, procure em sua caixa de spam e, ainda não encontrando, entre em contato com a equipe de Suporte <span style="font-size:11px;">suporte@mulheresbemresolvidas.com.br</span></p>
                </li>

                <li>
                    <h3>As aulas são todas on-line?</h3>
                    <p>Sim, todas as aulas são online em vídeo com disponibilização de materiais de apoios como ebooks em pdf e audio mp3, não temos cursos presenciais. A partir do momento da efetivação do seu pagamento em nosso sistema, terá acesso imediato ao conteúdo integral de curso, os dados de acesso serão enviamos por e-mail a você.</p>
                </li>

                <li>
                    <h3>As aulas são todas on-line?</h3>
                    <p>Sim, todas as aulas são online em vídeo com disponibilização de materiais de apoios como ebooks em pdf e audio mp3, não temos cursos presenciais. A partir do momento da efetivação do seu pagamento em nosso sistema, terá acesso imediato ao conteúdo integral de curso, os dados de acesso serão enviamos por e-mail a você.</p>
                </li>

            </ul>
        </div>

    </div>

    <div class="container-fluid text-center titulo12">

        <h1 class="t1 col-md-12">O reconhecimento<br>
            desse trabalho</h1>
        <hr class="bar" />
        <p class="text-center">Conheça alguns dos lugares que<br> meu trabalho foi reconhecido.</b></p>

        <div class="container">
            <br>
            <div class="col-md-6">
                <a href="https://www.youtube.com/watch?v=Kvk6QIkDjiI" class="html5lightbox"><img src="assets/images/videoplay.jpg" class="img-responsive " /></a>
            </div>

            <div class="col-md-5">
                <p class="textovideo">
                    O reconhecimento e o sucesso do trabalho são tão grandes que hoje eu sou convidada para dar entrevistas nos maiores veículos de comunicação do Brasil:<br>
                    Bolsa de Mulher, Catraca Livre, Marie Claire,
                    Glamour, Programa Terra Viva da Bandeirantes, Globo.com, entre outros.
                    <br><br>
                    Eu inclusive tive a prazer de realizar o sonho de ser entrevistada no <b><span style="color:#df2126">Programa no Jô</span></b>.
                </p>
            </div>

        </div>

        <br><br><br><br>
        <div class="container">
            <div class="col-md-4">
                <div class="center-block" style="float:none; width:180px">
                    <img src="assets/images/circle-jo.png" width="170" class="img-responsive" />
                    <h3>Jô Soares</h3>
                    <h4>Rede Globo</h4>
                </div>
            </div>
            <div class="col-md-4">
                <div class="center-block" style="float:none; width:180px">
                    <img src="assets/images/circle-catia.png" width="170" class="img-responsive" />
                    <h3>Catia Fonseca</h3>
                    <h4>TV Gazeta</h4>
                </div>
            </div>
            <div class="col-md-4">
                <div class="center-block" style="float:none; width:180px">
                    <img src="assets/images/renata.png" width="170" class="img-responsive"  />
                    <h3>Renata Maron</h3>
                    <h4>Rede Bandeirantes</h4>
                </div>
            </div>
        </div>

    </div>
    <br><br><br>
    <div class="container-fluid text-center titulo13">

        <h1 class="t1 col-md-12">Peça agora nosso contato<br>
            para saber mais
            desse trabalho</h1>
        <hr class="bar" />

        <p class="text-center">Nós receberemos sua solicitação<br>
            e rapidamente entraremos em contato</p>
    </div>
    <br><br>
    <div class="container-fluid contato">
        <div class="container">
            <div class="col-md-6">
                <div class="center-block centercatia">
                    <br><br>
                    <img src="assets/images/catia-contato.png" class="img-responsive catiacontato" />
                    <h4>"Eu acredito que toda mulher pode e merece ser feliz"</h4>
                    <p>
                        Cátia Damasceno é fisioterapeuta, especializada em uroginecologia e iniciou seu trabalho ensinando exercícios de ginástica íntima para o fortalecimento da musculatura de mulheres com problemas de flacidez íntima após o parto. Desde então se especializou em saúde feminina e ao longo de 12 anos, seus cursos e palestras já ajudaram milhares de mulheres em todo o Brasil.
                    </p>
                </div>
            </div>

            <div class="col-md-6 form" id="contato">

                <form class="form-horizontal" action="" method="post">

                    <div class="form-group">
                        <h4>Entraremos em contato assim que enviar seu pedido</h4>
                        <label><p>Nome*: </p></label>
                        <input type="text" class="form-control" name="nome" placeholder="Digite seu nome">
                    </div>

                    <div class="form-group">
                        <label><p>Telefone*: </p></label>
                        <input type="text" name="telefone" class="form-control" placeholder="Digite seu telefone">
                    </div>

                    <div class="form-group">
                        <label><p>E-mail*: </p></label>
                        <input type="email" name="email" class="form-control" placeholder="Digite seu email">
                    </div>

                    <div class="form-group">
                        <label><p>Mensagem: </p></label>
                        <br>
                        <textarea class="form-control" placeholder="Digite sua mensagem" name="mensagem"></textarea>
                    </div>

                    <div class="form-group">
                        <button type="submit" name="enviar" class="form-control btn btn-success col-md-12">Quero saber mais sobre o curso</button>
                    </div>

                    <p style="color:#727272; text-align: center"><i class="fa fa-lock" aria-hidden="true"></i> Site seguro, seus dados estão protegidos.</p>

                </form>
                <?php
                if(isset($_POST['enviar'])){

                    echo
                    '<div class="alert alert-success" role="alert">
					      <a href="#" class="alert-link text-center"><p>Seus dados foram enviados com sucesso.</p></a>
					    </div>
						';
                    // Abre ou cria o arquivo registro.txt
                    // "a" representa que o arquivo é aberto para ser escrito
                    $fp = fopen("registros-pp.txt", "a");

                    // Escreve "exemplo de escrita" no bloco1.txt
                    $escreve = fwrite($fp,
                        "=====================================\r\n Nome: "
                        .$_POST['nome']."\r\n Telefone: ".$_POST['telefone']."\r\n Email: ".$_POST['email']."\r\n Mensagem: ".$_POST['mensagem']."\r\n=====================================\r\n"
                    );

                    // Fecha o arquivo
                    fclose($fp);

                }

                ?>


            </div>
        </div>
    </div>

</div>


