<!-- Home -->
<section id="home" class="home-default">

    <div class="owl-slideshow bg-carousel home-full-carousel" data-auto-play="10500">
        <div class="bg-image bg-image-1"></div>
        <div class="bg-image bg-image-2"></div>
    </div>
    <div class="overlay overlay-black editable-alpha" data-alpha="70"></div>
    <div class="container dark vertical-center">
        <div class="row">
            <div class="col-md-6 col-lg-5 vertical-center">
                <div class="owl-carousel margin-bottom-20 animated" data-animation="zoomIn" data-single-item="true" data-auto-play="7500" data-pagination="true">
                    <div>
                        <span class="sep sep-primary"></span>
                        <h4 class="text-uppercase">Quero aprender <strong>Lógica de Programação</strong></h4>
                        <a href="#" class="btn btn-primary">Eu quero Lógica!</a>
                    </div>
                    <div>
                        <span class="sep sep-primary"></span>
                        <h4 class="text-uppercase"><strong>PHP</strong> para quem não sabe <strong>NADA</strong> e até para os mais <strong>experientes</strong>.</h4>
                        <a href="#" class="btn btn-primary">Eu quero PHP!</a>
                    </div>
                    <div>
                        <span class="sep sep-primary"></span>
                        <h4 class="text-uppercase">Aplicativos <strong>Android?</strong> Eu quero  <strong>aprender</strong> agora! </h4>
                        <a href="#" class="btn btn-primary">Eu quero Android!</a>
                    </div>
                    <div>
                        <span class="sep sep-primary"></span>
                        <h4 class="text-uppercase">Desenvolvimento <strong>JAVA</strong> é o que procuro <strong>Java Naguila Java!</strong></h4>
                        <a href="#" class="btn btn-primary">Eu quero Java!</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-5 col-lg-offset-2 vertical-center">
                <div class="sign-in-box dark animated" data-animation="flipInX">
                    <div class="sign-in-head bg-black-transparent">
                        <span class="pull-left icon icon-lg margin-bottom-5"><i class="fa fa-download text-primary"></i></span>
                        <div class="left-space-lg">
                            <h5 class="text-uppercase margin-bottom-0"><strong>Baixe nosso ebook</strong> e tenha acesso a vídeos exclusivos!</h5>
                            <p class="lead text-muted font-alt margin-bottom-0">Programação de um jeito que <b>você nunca viu antes</b>, conteúdos gratuitos que vão te destacar e acelerar seu aprendizado até <b>10x mais!</b></p>
                        </div>
                    </div>
                    <div class="sign-in-content bg-primary">
                        <form id="sign-in-form" method="post" action="https://virtudedigital.activehosted.com/proc.php" id="_form_1_">
                            <input type="hidden" name="u" value="1" />
                            <input type="hidden" name="f" value="1" />
                            <input type="hidden" name="s" />
                            <input type="hidden" name="c" value="0" />
                            <input type="hidden" name="m" value="0" />
                            <input type="hidden" name="act" value="sub" />
                            <input type="hidden" name="v" value="2" />
                            <div class="form-group form-group-lg margin-bottom-1">
                                <input type="text" id="nome" name="fullname" class="form-control bg-white margin-bottom-5" placeholder="Digite seu nome" required>
                            </div>


                            <div class="form-group form-group-lg margin-bottom-2">
                                <input type="text" id="emailSigned" name="email" class="form-control bg-white margin-bottom-5" placeholder="Deixe aqui seu melhor e-mail!" required>
                            </div>

                            <div class="form-group form-group-lg margin-bottom-0">
                                <select name="field[1]" id="curso" class="form-control bg-white margin-bottom-3" required>
                                    <option value="" disabled selected>Linguagem de Interesse</option>
                                    <option value="HTML5 & CSS3">HTML5 & CSS3</option>
                                    <option value="Java">Java</option>
                                    <option value="PHP">PHP</option>
                                    <option value="Android">Android</option>
                                    <option value="Lógica de Programação">Lógica de Programação</option>
                                    <option value="Banco de Dados MySql">Banco de Dados MySql</option>
                                </select>
                            </div>

                            <div class="form-bottom-bar clearfix">
                                <span class="checkbox-group pull-left"><input id="acceptRules" name="acceptRules" type="checkbox" /><label for="acceptRules" class="checkbox-label">Concordo com os <a href="#" data-toggle="modal" data-target="#rulesModal">termos</a>.</label></span>
                                <button type="submit" name="ebook" class="btn btn-filled btn-primary-dark pull-right"><i class="icon-before fa fa-plus"></i>Baixar agora!</button>
                            </div>
                        </form>
                        <script type="text/javascript">
                            window.cfields = [];
                            window._show_thank_you = function(id, message, trackcmp_url) {
                                var form = document.getElementById('_form_' + id + '_'), thank_you = form.querySelector('._form-thank-you');
                                form.querySelector('._form-content').style.display = 'none';
                                thank_you.innerHTML = message;
                                thank_you.style.display = 'block';
                                if (typeof(trackcmp_url) != 'undefined' && trackcmp_url) {
                                    // Site tracking URL to use after inline form submission.
                                    _load_script(trackcmp_url);
                                }
                                if (typeof window._form_callback !== 'undefined') window._form_callback(id);
                            };
                            window._show_error = function(id, message, html) {
                                var form = document.getElementById('_form_' + id + '_'), err = document.createElement('div'), button = form.querySelector('button'), old_error = form.querySelector('._form_error');
                                if (old_error) old_error.parentNode.removeChild(old_error);
                                err.innerHTML = message;
                                err.className = '_error-inner _form_error _no_arrow';
                                var wrapper = document.createElement('div');
                                wrapper.className = '_form-inner';
                                wrapper.appendChild(err);
                                button.parentNode.insertBefore(wrapper, button);
                                document.querySelector('[id^="_form"][id$="_submit"]').disabled = false;
                                if (html) {
                                    var div = document.createElement('div');
                                    div.className = '_error-html';
                                    div.innerHTML = html;
                                    err.appendChild(div);
                                }
                            };
                            window._load_script = function(url, callback) {
                                var head = document.querySelector('head'), script = document.createElement('script'), r = false;
                                script.type = 'text/javascript';
                                script.charset = 'utf-8';
                                script.src = url;
                                if (callback) {
                                    script.onload = script.onreadystatechange = function() {
                                        if (!r && (!this.readyState || this.readyState == 'complete')) {
                                            r = true;
                                            callback();
                                        }
                                    };
                                }
                                head.appendChild(script);
                            };
                            (function() {
                                if (window.location.search.search("excludeform") !== -1) return false;
                                var getCookie = function(name) {
                                    var match = document.cookie.match(new RegExp('(^|; )' + name + '=([^;]+)'));
                                    return match ? match[2] : null;
                                }
                                var setCookie = function(name, value) {
                                    var now = new Date();
                                    var time = now.getTime();
                                    var expireTime = time + 1000 * 60 * 60 * 24 * 365;
                                    now.setTime(expireTime);
                                    document.cookie = name + '=' + value + '; expires=' + now + ';path=/';
                                }
                                var addEvent = function(element, event, func) {
                                    if (element.addEventListener) {
                                        element.addEventListener(event, func);
                                    } else {
                                        var oldFunc = element['on' + event];
                                        element['on' + event] = function() {
                                            oldFunc.apply(this, arguments);
                                            func.apply(this, arguments);
                                        };
                                    }
                                }
                                var _removed = false;
                                var form_to_submit = document.getElementById('_form_1_');
                                var allInputs = form_to_submit.querySelectorAll('input, select, textarea'), tooltips = [], submitted = false;

                                var getUrlParam = function(name) {
                                    var regexStr = '[\?&]' + name + '=([^&#]*)';
                                    var results = new RegExp(regexStr, 'i').exec(window.location.href);
                                    return results != undefined ? decodeURIComponent(results[1]) : false;
                                };

                                for (var i = 0; i < allInputs.length; i++) {
                                    var regexStr = "field\\[(\\d+)\\]";
                                    var results = new RegExp(regexStr).exec(allInputs[i].name);
                                    if (results != undefined) {
                                        allInputs[i].dataset.name = window.cfields[results[1]];
                                    } else {
                                        allInputs[i].dataset.name = allInputs[i].name;
                                    }
                                    var fieldVal = getUrlParam(allInputs[i].dataset.name);

                                    if (fieldVal) {
                                        if (allInputs[i].type == "radio" || allInputs[i].type == "checkbox") {
                                            if (allInputs[i].value == fieldVal) {
                                                allInputs[i].checked = true;
                                            }
                                        } else {
                                            allInputs[i].value = fieldVal;
                                        }
                                    }
                                }

                                var remove_tooltips = function() {
                                    for (var i = 0; i < tooltips.length; i++) {
                                        tooltips[i].tip.parentNode.removeChild(tooltips[i].tip);
                                    }
                                    tooltips = [];
                                };
                                var remove_tooltip = function(elem) {
                                    for (var i = 0; i < tooltips.length; i++) {
                                        if (tooltips[i].elem === elem) {
                                            tooltips[i].tip.parentNode.removeChild(tooltips[i].tip);
                                            tooltips.splice(i, 1);
                                            return;
                                        }
                                    }
                                };
                                var create_tooltip = function(elem, text) {
                                    var tooltip = document.createElement('div'), arrow = document.createElement('div'), inner = document.createElement('div'), new_tooltip = {};
                                    if (elem.type != 'radio' && elem.type != 'checkbox') {
                                        tooltip.className = '_error';
                                        arrow.className = '_error-arrow';
                                        inner.className = '_error-inner';
                                        inner.innerHTML = text;
                                        tooltip.appendChild(arrow);
                                        tooltip.appendChild(inner);
                                        elem.parentNode.appendChild(tooltip);
                                    } else {
                                        tooltip.className = '_error-inner _no_arrow';
                                        tooltip.innerHTML = text;
                                        elem.parentNode.insertBefore(tooltip, elem);
                                        new_tooltip.no_arrow = true;
                                    }
                                    new_tooltip.tip = tooltip;
                                    new_tooltip.elem = elem;
                                    tooltips.push(new_tooltip);
                                    return new_tooltip;
                                };
                                var resize_tooltip = function(tooltip) {
                                    var rect = tooltip.elem.getBoundingClientRect();
                                    var doc = document.documentElement, scrollPosition = rect.top - ((window.pageYOffset || doc.scrollTop)  - (doc.clientTop || 0));
                                    if (scrollPosition < 40) {
                                        tooltip.tip.className = tooltip.tip.className.replace(/ ?(_above|_below) ?/g, '') + ' _below';
                                    } else {
                                        tooltip.tip.className = tooltip.tip.className.replace(/ ?(_above|_below) ?/g, '') + ' _above';
                                    }
                                };
                                var resize_tooltips = function() {
                                    if (_removed) return;
                                    for (var i = 0; i < tooltips.length; i++) {
                                        if (!tooltips[i].no_arrow) resize_tooltip(tooltips[i]);
                                    }
                                };
                                var validate_field = function(elem, remove) {
                                    var tooltip = null, value = elem.value, no_error = true;
                                    remove ? remove_tooltip(elem) : false;
                                    if (elem.type != 'checkbox') elem.className = elem.className.replace(/ ?_has_error ?/g, '');
                                    if (elem.getAttribute('required') !== null) {
                                        if (elem.type == 'radio' || (elem.type == 'checkbox' && /any/.test(elem.className))) {
                                            var elems = form_to_submit.elements[elem.name];
                                            no_error = false;
                                            for (var i = 0; i < elems.length; i++) {
                                                if (elems[i].checked) no_error = true;
                                            }
                                            if (!no_error) {
                                                tooltip = create_tooltip(elem, "Please select an option.");
                                            }
                                        } else if (elem.type =='checkbox') {
                                            var elems = form_to_submit.elements[elem.name], found = false, err = [];
                                            no_error = true;
                                            for (var i = 0; i < elems.length; i++) {
                                                if (elems[i].getAttribute('required') === null) continue;
                                                if (!found && elems[i] !== elem) return true;
                                                found = true;
                                                elems[i].className = elems[i].className.replace(/ ?_has_error ?/g, '');
                                                if (!elems[i].checked) {
                                                    no_error = false;
                                                    elems[i].className = elems[i].className + ' _has_error';
                                                    err.push("Checking %s is required".replace("%s", elems[i].value));
                                                }
                                            }
                                            if (!no_error) {
                                                tooltip = create_tooltip(elem, err.join('<br/>'));
                                            }
                                        } else if (elem.tagName == 'SELECT') {
                                            var selected = true;
                                            if (elem.multiple) {
                                                selected = false;
                                                for (var i = 0; i < elem.options.length; i++) {
                                                    if (elem.options[i].selected) {
                                                        selected = true;
                                                        break;
                                                    }
                                                }
                                            } else {
                                                for (var i = 0; i < elem.options.length; i++) {
                                                    if (elem.options[i].selected && !elem.options[i].value) {
                                                        selected = false;
                                                    }
                                                }
                                            }
                                            if (!selected) {
                                                no_error = false;
                                                tooltip = create_tooltip(elem, "Please select an option.");
                                            }
                                        } else if (value === undefined || value === null || value === '') {
                                            elem.className = elem.className + ' _has_error';
                                            no_error = false;
                                            tooltip = create_tooltip(elem, "This field is required.");
                                        }
                                    }
                                    if (no_error && elem.name == 'email') {
                                        if (!value.match(/^[\+_a-z0-9-'&=]+(\.[\+_a-z0-9-']+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,})$/i)) {
                                            elem.className = elem.className + ' _has_error';
                                            no_error = false;
                                            tooltip = create_tooltip(elem, "Enter a valid email address.");
                                        }
                                    }
                                    if (no_error && /date_field/.test(elem.className)) {
                                        if (!value.match(/^\d\d\d\d-\d\d-\d\d$/)) {
                                            elem.className = elem.className + ' _has_error';
                                            no_error = false;
                                            tooltip = create_tooltip(elem, "Enter a valid date.");
                                        }
                                    }
                                    tooltip ? resize_tooltip(tooltip) : false;
                                    return no_error;
                                };
                                var needs_validate = function(el) {
                                    return el.name == 'email' || el.getAttribute('required') !== null;
                                };
                                var validate_form = function(e) {
                                    var err = form_to_submit.querySelector('._form_error'), no_error = true;
                                    if (!submitted) {
                                        submitted = true;
                                        for (var i = 0, len = allInputs.length; i < len; i++) {
                                            var input = allInputs[i];
                                            if (needs_validate(input)) {
                                                if (input.type == 'text') {
                                                    addEvent(input, 'blur', function() {
                                                        this.value = this.value.trim();
                                                        validate_field(this, true);
                                                    });
                                                    addEvent(input, 'input', function() {
                                                        validate_field(this, true);
                                                    });
                                                } else if (input.type == 'radio' || input.type == 'checkbox') {
                                                    (function(el) {
                                                        var radios = form_to_submit.elements[el.name];
                                                        for (var i = 0; i < radios.length; i++) {
                                                            addEvent(radios[i], 'click', function() {
                                                                validate_field(el, true);
                                                            });
                                                        }
                                                    })(input);
                                                } else if (input.tagName == 'SELECT') {
                                                    addEvent(input, 'change', function() {
                                                        validate_field(input, true);
                                                    });
                                                }
                                            }
                                        }
                                    }
                                    remove_tooltips();
                                    for (var i = 0, len = allInputs.length; i < len; i++) {
                                        var elem = allInputs[i];
                                        if (needs_validate(elem)) {
                                            if (elem.tagName.toLowerCase() !== "select") {
                                                elem.value = elem.value.trim();
                                            }
                                            validate_field(elem) ? true : no_error = false;
                                        }
                                    }
                                    if (!no_error && e) {
                                        e.preventDefault();
                                    }
                                    resize_tooltips();
                                    return no_error;
                                };
                                addEvent(window, 'resize', resize_tooltips);
                                addEvent(window, 'scroll', resize_tooltips);
                                window._old_serialize = null;
                                if (typeof serialize !== 'undefined') window._old_serialize = window.serialize;
                                _load_script("//d3rxaij56vjege.cloudfront.net/form-serialize/0.3/serialize.min.js", function() {
                                    window._form_serialize = window.serialize;
                                    if (window._old_serialize) window.serialize = window._old_serialize;
                                });
                                var form_submit = function(e) {
                                    e.preventDefault();
                                    if (validate_form()) {
                                        // use this trick to get the submit button & disable it using plain javascript
                                        document.querySelector('[id^="_form"][id$="_submit"]').disabled = true;
                                        var serialized = _form_serialize(document.getElementById('_form_1_'));
                                        var err = form_to_submit.querySelector('._form_error');
                                        err ? err.parentNode.removeChild(err) : false;
                                        _load_script('https://virtudedigital.activehosted.com/proc.php?' + serialized + '&jsonp=true');
                                    }
                                    return false;
                                };
                                addEvent(form_to_submit, 'submit', form_submit);
                            })();

                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
<!-- Home / End -->

<!-- Content -->
<div id="content">

    <!-- Section -->
    <section class="section padded-vertical-70 container">
        <div class="row">
            <div class="col-lg-10">
                <div class="section-title margin-bottom-40">
                    <h4 class="text-uppercase margin-bottom-0">A <strong>Fábrica de Desenvolvedores</strong></h4>
                    <span class="sep sep-primary sep-animated"></span>
                    <p class="lead font-alt">A missão é desmistificar a barreira que separa a difculdade da compreensão, ter acesso rápido ao que foi aprendido sem a necessidade de revisões exaustivas ou retrabalhos.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- Icon Box -->
            <div class="col-md-3 col-sm-6 icon-box icon-box-hover">
                <span class="icon icon-sm icon-circle icon-primary margin-bottom-20 animated" data-animation="bounceIn" data-animation-delay="400"><i class="fa fa-book"></i></span>
                <h5 class="margin-bottom-0"><strong>E-books</strong> Freemium</h5>
                <p class="text-muted">Estaremos disponibilizando e-books de primeiríssima para acelerar seu rendimento e alavancar sua carreira no mercado.</p>
                <a href="#" class="underline-link text-uppercase text-primary">Saiba Mais</a>
            </div>
            <!-- Icon Box -->
            <div class="col-md-3 col-sm-6 icon-box icon-box-hover">
                <span class="icon icon-sm icon-circle icon-primary margin-bottom-20 animated" data-animation="bounceIn" data-animation-delay="600"><i class="fa fa-video-camera"></i></span>
                <h5 class="margin-bottom-0"><strong>Aulas</strong> Exclusivas</h5>
                <p class="text-muted">Receba aulas e dicas de um jeito que você nunca viu. Programar nunca foi tão fácil!</p>
                <a href="#" class="underline-link text-uppercase text-primary">Saiba Mais</a>
            </div>
            <!-- Icon Box -->
            <div class="col-md-3 col-sm-6 icon-box icon-box-hover">
                <span class="icon icon-sm icon-circle icon-primary margin-bottom-20 animated" data-animation="bounceIn" data-animation-delay="800"><i class="fa fa-camera"></i></span>
                <h5 class="margin-bottom-0"><strong>Portifólio diferenciado</strong></h5>
                <p class="text-muted">Juntos desenvolveremos projetos que o mercado vai #pirar! Diversidade de projetos para web em diferentes plataformas.</p>
                <a href="#" class="underline-link text-uppercase text-primary">Saiba Mais</a>
            </div>
            <!-- Icon Box -->
            <div class="col-md-3 col-sm-6 icon-box icon-box-hover">
                <span class="icon icon-sm icon-circle icon-filled icon-primary margin-bottom-20 animated" data-animation="bounceIn" data-animation-delay="1000"><i class="fa fa-heart"></i></span>
                <h5 class="margin-bottom-0">+<strong>Rede</strong> de desenvolvimento!</h5>
                <p class="text-muted">Esteja interado nos grupos de desenvolvedores em fabricação e já lançados no mercado pela Fábrica de Desenvolvedores #FADEV, #sóVamo?</p>
                <a href="#" class="underline-link text-uppercase text-primary">Saiba Mais</a>
            </div>
        </div>
    </section>

    <!-- Section -->
    <section class="section padded-vertical-70">
        <div class="bg-image bg-image-4"></div>
        <div class="overlay overlay-white editable-alpha" data-alpha="10"></div>
        <div class="container">
            <span class="pull-left icon icon-lg margin-bottom-0 animated" data-animation="bounceIn" data-animation-delay="400"><i class="fa fa-play-circle-o text-primary"></i></span>
            <div class="left-space-lg animated" data-animation="fadeInRight" data-animation-delay="400">
                <h4 class="text-uppercase margin-bottom-0"><strong>Tenha acesso</strong> a aulas exclusivas</h4>
                <p class="lead text-muted font-alt">Cadastre-se e prepare-se para se tornar um desenvolvedor de ponta!</p>
                <a href="#" class="btn btn-primary btn-filled">Quero Acesso!</a><a href="#" class="btn btn-link">Saiba Mais</a>
            </div>
        </div>
    </section>

    <!-- Section
    <section class="section padded-vertical-70 container">
        <div class="row">
            <div class="col-lg-10">
            	<div class="section-title margin-bottom-40">
                    <h4 class="text-uppercase margin-bottom-5"><strong>Aulas</strong> gratuitas</h4>
                    <span class="sep sep-primary sep-animated"></span>
                    <p class="lead font-alt">Não são simplesmente conteúdos gratuitos, tenho certeza que você terá uma visão diferente do que é programação e do quão fácil é dominar a arte de solucionar problemas.</p>
                </div>
             </div>
        </div>
        <div class="row">
        	<!-- Post  
            <div class="post post-horizontal col-md-6 clearfix">
                <div class="post-image-thumb animated" data-animation="fadeInLeft" data-animation-delay="400">
                    <img src="images/blog/post01-thumb.jpg" alt="" />
                </div>
                <div class="post-content">
                    <div class="post-labels">
                        <a href="#" class="label label-primary animated" data-animation="flipInX" data-animation-delay="400">Webdesign</a>
                        <a href="#" class="label label-primary animated" data-animation="flipInX" data-animation-delay="600">Webdevelopment</a>
                    </div>
                    <h5 class="post-title"><a href="#">Donec molestie in libero nec lobortis nec</a></h5>
                    <div class="post-meta">
                        <span><i class="fa fa-clock-o"></i><a href="#">24.05.2014</a></span>
                        <span><i class="fa fa-comment"></i><a href="#">2 Comments</a></span>
                    </div>
                    <p class="font-alt">Sed volutpat purus non odio maximus, eget ultrices mauris rutrum. Phasellus non diam in neque interdum gravida. </p>
                    <a href="#" class="btn btn-primary btn-xs">Read more</a>
                </div>
            </div>
            <!-- Post  
            <div class="post post-horizontal col-md-6 clearfix">
                <div class="post-image-thumb animated" data-animation="fadeInLeft" data-animation-delay="600">
                    <img src="images/blog/post02-thumb.jpg" alt="" />
                </div>
                <div class="post-content">
                    <div class="post-labels">
                        <span class="label label-primary animated" data-animation="flipInX" data-animation-delay="400">E-marketing</span>
                    </div>
                    <h5 class="post-title"><a href="#">Donec molestie in libero nec lobortis nec</a></h5>
                    <div class="post-meta">
                        <span><i class="fa fa-clock-o"></i><a href="#">24.05.2014</a></span>
                        <span><i class="fa fa-comment"></i><a href="#">2 Comments</a></span>
                    </div>
                    <p class="font-alt">Sed volutpat purus non odio maximus, eget ultrices mauris rutrum. Phasellus non diam in neque interdum gravida. </p>
                    <a href="#" class="btn btn-primary btn-xs">Read more</a>
                </div>
            </div>
            <!-- Post  
            <div class="post post-horizontal col-md-6 clearfix">
                <div class="post-image-thumb animated" data-animation="fadeInLeft" data-animation-delay="800">
                    <img src="images/blog/post03-thumb.jpg" alt="" />
                </div>
                <div class="post-content">
                    <div class="post-labels">
                        <span class="label label-primary animated" data-animation="flipInX" data-animation-delay="400">Webdesign</span>
                    </div>
                    <h5 class="post-title"><a href="#">Donec molestie in libero nec lobortis nec</a></h5>
                    <div class="post-meta">
                        <span><i class="fa fa-clock-o"></i><a href="#">24.05.2014</a></span>
                        <span><i class="fa fa-comment"></i><a href="#">2 Comments</a></span>
                    </div>
                    <p class="font-alt">Sed volutpat purus non odio maximus, eget ultrices mauris rutrum. Phasellus non diam in neque interdum gravida. </p>
                    <a href="#" class="btn btn-primary btn-xs">Read more</a>
                </div>
            </div>
            <!-- Post 
            <div class="post post-horizontal col-md-6 clearfix">
                <div class="post-image-thumb animated" data-animation="fadeInLeft" data-animation-delay="1000">
                    <img src="images/blog/post04-thumb.jpg" alt="" />
                </div>
                <div class="post-content">
                    <div class="post-labels">
                        <span class="label label-primary animated" data-animation="flipInX" data-animation-delay="400">Social Media</span>
                    </div>
                    <h5 class="post-title"><a href="#">Donec molestie in libero nec lobortis nec</a></h5>
                    <div class="post-meta">
                        <span><i class="fa fa-clock-o"></i><a href="#">24.05.2014</a></span>
                        <span><i class="fa fa-comment"></i><a href="#">2 Comments</a></span>
                    </div>
                    <p class="font-alt">Sed volutpat purus non odio maximus, eget ultrices mauris rutrum. Phasellus non diam in neque interdum gravida. </p>
                    <a href="#" class="btn btn-primary btn-xs">Read more</a>
                </div>
            </div>
        </div>
    </section>
    
    <!-- Section -->
    <section class="section padded-vertical-70 dark">
        <div class="bg-image parallax bg-image-3"></div>
        <div class="overlay overlay-black editable-alpha" data-alpha="70"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- Twitter -->
                    <div class="tweet tweet-horizontal"></div>
                </div>
            </div>
        </div>
    </section>

</div>
<!-- Content / End -->


