<div class="nav-bar clearfix">
    <!-- Logo -->
    <div class="logo pull-left">
        <a href="<?=HOMEP;?>"><img src="assets/images/logo-black.png" alt="#FADEV" title="Fábrica de Desenvolvedores" /></a>
    </div>
    <!-- Mobile Nav Toggle -->
    <a href="" class="mobile-menu-toggle pull-right"></a>
    <!-- Social Icons -->
    <div class="social-icons text-muted pull-right margin-left-20 hidden-sm hidden-xs">
        <a href="https://www.facebook.com/LudsonAlmeidaDesenvolvedor/" target="_blank" class="icon icon-xs icon-facebook"><i class="fa fa-facebook"></i></a>
        <a href="#" class="icon icon-xs icon-youtube" target="_blank"><i class="fa fa-youtube"></i></a>
        <a href="#" class="icon icon-xs icon-twitter" target="_blank"><i class="fa fa-twitter"></i></a>
        <a href="#" class="icon icon-xs icon-google-plus" target="_blank"><i class="fa fa-google-plus"></i></a>
    </div>
    <!-- Main Navigation-->
    <ul class="menu nav nav-main text-uppercase pull-right margin-left-20 dropdown-dark">
        <li><a href="<?=HOMEP;?>">Home</a></li>
        <li><a href="<?=HOMEP;?>">E-books</a></li>
        <li><a href="/contato">Contato</a></li>
    </ul>
</div>