<?php
    $registros = $this->view->registros;

?>
<section class="content">
    <section class="widget">
        <header>
            <span class="icon">&#128196;</span>
            <hgroup>
                <h1>Registros</h1>
                <h2>Telefones submetidos</h2>
            </hgroup>

            <aside>
                <button class="ico-font">?</button>
                <a href="/admin/registros/exportar"><span class="button blue">Exportar</span></a>
            </aside>

        </header>

            <div class="content">
                <table id="myTable" border="0" width="100">
                    <thead>
                    <tr>
                        <th class="header">Registro</th>
                        <th class="header">Nome</th>
                        <th class="header">Telefone</th>
                        <th class="header">E-mail</th>
                        <th class="header">Mensagem</th>
                        <th class="header" colspan="3">Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                        foreach($registros as $registro):
                    ?>
                    <tr class="odd">
                        <td align="center">#<?php echo $registro['id'];?></td>
                        <td><?php echo $registro['nome'];?></td>
                        <td><?php echo $registro['telefone'];?></td>
                        <td><?php echo $registro['email'];?></td>
                        <td><?php echo $registro['mensagem'];?></td>
                        <td><a href="registros/editar?id=<?php echo $registro['id'];?>">Editar</a> | <a href="registros/apagar?id=<?php echo $registro['id'];?>">Excluir</a></td>

                    </tr>
                    <?php endforeach;?>
                    </tbody>

                </table>
            </div>

        <?php echo $this->view->paginator;?>

    </section>
</section>

