<!-- Right Column -->
<div class="col-md-4">

    <!-- Navigation list -->
    <h5 class="text-uppercase">Categorias</h5>
    <ul class="nav nav-sidebar margin-bottom-40">
        <li><a href="#">Webdesign</a></li>
        <li><a href="#">E-Commercie</a></li>
        <li><a href="#">Social Media</a></li>
        <li><a href="#">Webdevelopment</a></li>
        <li><a href="#">Graphic Design</a></li>
    </ul>

    <!-- Tweets -->
    <h5 class="text-uppercase">Últimos <strong>Tweets</strong></h5>
    <div class="tweet font-alt margin-bottom-40"></div>

    <!-- Ad -->
    <img src="<?=HOMEP;?>/assets/images/ads/ad_250x250.jpg" class="margin-bottom-40 center-block" alt="" />


</div>