<?php

?>

<!-- Title Bar -->
<div id="page-title">

    <div class="title-bar dark bg-black padded-vertical-70">
        <div class="bg-image bg-image-3"></div>
        <div class="overlay overlay-black editable-alpha" data-alpha="80"></div>
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <span class="icon icon-lg icon-circle icon-primary margin-bottom-20 animated" data-animation="bounceIn"><i class="fa fa-puzzle-piece"></i></span>
                    <h1 class="text-uppercase margin-bottom-0 animated" data-animation="flipInX" data-animation-delay="200"><strong>Curso: </strong> Lógica de Programação</h1>
                    <span class="sep sep-primary"></span>
                    <div class="font-alt text-muted margin-bottom-20">Etiam porta ipsum at nibh faucibus dictum. Proin augue diam, luctus eu lobortis at, varius ut ipsum. Pellentesque non cursus arcu, at auctor dui. </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Breadcrumbs -->
    <div class="bordered-bottom">
        <div class="container">
            <ol class="breadcrumb text-uppercase">
                <li><a href="#">Home</a></li>
                <li class="active">Cursos</li>
                <li class="active">Lógica de Programação</li>
            </ol>
        </div>
    </div>

</div>
<!-- Title Bar / End -->

<!-- Content -->
<div id="content">

    <section class="container">
        <div class="row padded-vertical-40">
            <div class="col-md-3">
                <h4 class="text-light"><strong>Who</strong> we are?</h4>
                <p class="lead">Praesent eros justo, convallis non mauris in, varius tincidunt ex. Suspendisse mattis erat et est molestie aliquet.</p>
                <p>Suspendisse mattis erat et est molestie aliquet consectetur adipiscing elit. Praesent eros justo, convallis non mauris in, varius tincidunt ex. Suspendisse mattis erat et est molestie aliquet.</p>
                <p><a href="#" class="btn btn-primary btn-sm">Our Services</a> <a href="#" class="btn btn-default btn-sm">Contact Us</a></p>
            </div>
            <div class="col-md-9">
                <h4 class="text-light"><strong>Why</strong> Us?</h4>
                <div class="row">
                    <!-- Icon Box -->
                    <div class="col-sm-4 icon-box icon-box-hover">
                        <span class="icon icon-sm icon-circle icon-primary margin-bottom-20 animated" data-animation="bounceIn" data-animation-delay="400"><i class="fa fa-book"></i></span>
                        <h5 class="margin-bottom-0">5 Premium <strong>Ebooks</strong></h5>
                        <p class="text-muted">Class aptent taciti sociosqu ad litora torquent per conubia nostra.</p>
                    </div>
                    <!-- Icon Box -->
                    <div class="col-sm-4 icon-box icon-box-hover">
                        <span class="icon icon-sm icon-circle icon-primary margin-bottom-20 animated" data-animation="bounceIn" data-animation-delay="400"><i class="fa fa-video-camera"></i></span>
                        <h5 class="margin-bottom-0">6 <strong>Video</strong> Courses</h5>
                        <p class="text-muted">Class aptent taciti sociosqu ad litora torquent per conubia nostra.</p>
                    </div>
                    <!-- Icon Box -->
                    <div class="col-sm-4 icon-box icon-box-hover">
                        <span class="icon icon-sm icon-circle icon-primary margin-bottom-20 animated" data-animation="bounceIn" data-animation-delay="400"><i class="fa fa-camera"></i></span>
                        <h5 class="margin-bottom-0">5 <strong>PSD Files</strong></h5>
                        <p class="text-muted">Class aptent taciti sociosqu ad litora torquent per conubia nostra.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Section -->
    <section class="section padded-vertical-70 dark">
        <div class="bg-image bg-image-1"></div>
        <div class="overlay overlay-black editable-alpha" data-alpha="60"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-lg-offset-3 text-center">
                    <span class="icon icon-lg animated bounce-in"><i class="fa fa-download text-primary"></i></span>
                    <div class="margin-bottom-20">
                        <h4 class="text-uppercase margin-bottom-0"><strong>Get Access</strong> to free files!</h4>
                        <p class="lead text-muted font-alt">Sign up to be the first to get all of my best business advices for free to your inbox.</p>
                    </div>
                    <form id="sign-in-form">
                        <div class="form-group form-group-lg">
                            <input type="text" id="emailSigned" name="emailSigned" class="form-control bg-white margin-bottom-5" placeholder="Tap here your e-mail address...">
                        </div>
                        <span class="checkbox-group margin-bottom-10"><input id="acceptRules" name="acceptRules" type="checkbox" checked/><label for="acceptRules" class="checkbox-label">I accept all the <a href="#" data-toggle="modal" data-target="#rulesModal">rules</a></label></span>
                        <button type="submit" class="btn btn-primary btn-filled btn-lg"><i class="icon-before fa fa-plus"></i>Sign In!</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Section / End -->

