<div id="page-title">

    <div class="title-bar dark bg-black padded-vertical-60">
        <div class="bg-image bg-image-4"></div>
        <div class="overlay overlay-black editable-alpha" data-alpha="70"></div>
        <div class="container">
            <span class="sep sep-primary sep-no-top"></span>
            <h2 class="text-uppercase margin-bottom-0"><strong>Confirmação</strong></h2>
            <span class="text-xs text-muted text-uppercase">Quase tudo certo!</span>
        </div>
    </div>

    <!-- Breadcrumbs -->
    <div class="bordered-bottom">
        <div class="container">
            <ol class="breadcrumb text-uppercase">
                <li><a href="<?=HOMEP;?>">Home</a></li>
                <li class="active">Confirmação de E-mail</li>
            </ol>
        </div>
    </div>

</div>
<!-- Title Bar / End -->
<!-- Content -->
<div id="content">
    <br>
    <div class="row">
        <section class="container">

                <div class="alert alert-info" role="alert">
                    <h1>Quase tudo certo!</h1> <h3>Você acabou de receber um e-mail de confirmação.</h3>
                </div>
            <h4> Para que possamos validar seu e-mail basta acessar o link e se preparar para receber os melhores conteúdos para web.</h4>
            <h5>Verifique sua caixa de entrada, nos vemos logo mais! ;)</h5>
        </section>
    </div>
</div>