<div id="page-title">

    <div class="title-bar dark bg-black padded-vertical-60">
        <div class="bg-image bg-image-4"></div>
        <div class="overlay overlay-black editable-alpha" data-alpha="70"></div>
        <div class="container">
            <span class="sep sep-primary sep-no-top"></span>
            <h2 class="text-uppercase margin-bottom-0"><strong>Inscrição</strong></h2>
            <span class="text-xs text-muted text-uppercase">Fechou!</span>
        </div>
    </div>

    <!-- Breadcrumbs -->
    <div class="bordered-bottom">
        <div class="container">
            <ol class="breadcrumb text-uppercase">
                <li><a href="<?=HOMEP;?>">Home</a></li>
                <li class="active">Inscrição de E-mail</li>
            </ol>
        </div>
    </div>

</div>
<!-- Title Bar / End -->
<!-- Content -->
<div id="content">
    <br>
    <div class="row">
        <section class="container">

            <div class="alert alert-success" role="alert">
                <h1>Email inscrito com sucesso!</h1>
            </div>

            <h3>Seu e-mail foi validado.</h3><br>
            <h4> Tá pronto? É hora do show!</h4>

            <h5>Vamos programar my friend! Tamo junto.</h5>
            <h5>Ludson S. Almeida ;)</h5>
            <br>
        </section>
    </div>
</div>