<!-- Title Bar -->
<?php
?>
<div id="page-title">

    <div class="title-bar dark bg-black padded-vertical-60">
        <div class="bg-image bg-image-4"></div>
        <div class="overlay overlay-black editable-alpha" data-alpha="70"></div>
        <div class="container">
            <span class="sep sep-primary sep-no-top"></span>
            <h2 class="text-uppercase margin-bottom-0"><strong>Blog</strong></h2>
            <span class="text-xs text-muted text-uppercase">Artigos, Video-Aulas e mais... </span>
        </div>
    </div>

    <!-- Breadcrumbs -->
    <div class="bordered-bottom">
        <div class="container">
            <ol class="breadcrumb text-uppercase">
                <li><a href="<?=HOME;?>">Home</a></li>
                <li class="active">Blog</li>
            </ol>
        </div>
    </div>

</div>
<!-- Title Bar / End -->


<!-- Content -->
<div id="content">

    <div class="container">
        <div class="row padded-top-40">

            <!-- Left Column -->
            <div class="col-md-8">

                <div class="row posts-list">
                    <!-- Post  -->
                    <div class="post post-vertical col-md-6 clearfix">
                        <div class="post-image-thumb">
                            <img src="<?=HOMEP;?>/assets/images/blog/post01-thumb.jpg" alt="" />
                        </div>
                        <div class="post-content">
                            <div class="post-labels">
                                <a href="#" class="label label-primary animated" data-animation="flipInX" data-animation-delay="400">Webdesign</a>
                                <a href="#" class="label label-primary animated" data-animation="flipInX" data-animation-delay="600">Webdevelopment</a>
                            </div>
                            <h5 class="post-title"><a href="#">Working on new awesome themes for everyone!</a></h5>
                            <div class="post-meta">
                                <span><i class="fa fa-clock-o"></i><a href="#">24.05.2014</a></span>
                                <span><i class="fa fa-comment"></i><a href="#">2 Comentários</a></span>
                            </div>
                            <p class="font-alt">Suspendisse mattis erat et est molestie aliquet consectetur adipiscing elit. Praesent eros justo, convallis non mauris in, varius tincidunt ex. Suspendisse mattis erat et est molestie aliquet.</p>
                            <a href="#" class="btn btn-primary btn-xs">Leia Mais</a>
                        </div>
                    </div>
                    <!-- Post  -->
                    <div class="post post-vertical col-md-6 clearfix">
                        <div class="post-image-thumb">
                            <img src="<?=HOMEP;?>/assets/images/blog/post02-thumb.jpg" alt="" />
                        </div>
                        <div class="post-content">
                            <div class="post-labels">
                                <a href="#" class="label label-primary animated" data-animation="flipInX" data-animation-delay="400">Webdesign</a>
                                <a href="#" class="label label-primary animated" data-animation="flipInX" data-animation-delay="600">Webdevelopment</a>
                            </div>
                            <h5 class="post-title"><a href="#">Working on new awesome themes for everyone!</a></h5>
                            <div class="post-meta">
                                <span><i class="fa fa-clock-o"></i><a href="#">24.05.2014</a></span>
                                <span><i class="fa fa-comment"></i><a href="#">2 Comentários</a></span>
                            </div>
                            <p class="font-alt">Suspendisse mattis erat et est molestie aliquet consectetur adipiscing elit. Praesent eros justo, convallis non mauris in, varius tincidunt ex. Suspendisse mattis erat et est molestie aliquet.</p>
                            <a href="#" class="btn btn-primary btn-xs">Leia Mais</a>
                        </div>
                    </div>
                    <!-- Post  -->
                    <div class="post post-vertical col-md-6 clearfix">
                        <div class="post-image-thumb">
                            <img src="<?=HOMEP;?>/assets/images/blog/post03-thumb.jpg" alt="" />
                        </div>
                        <div class="post-content">
                            <div class="post-labels">
                                <a href="#" class="label label-primary animated" data-animation="flipInX" data-animation-delay="400">Webdesign</a>
                                <a href="#" class="label label-primary animated" data-animation="flipInX" data-animation-delay="600">Webdevelopment</a>
                            </div>
                            <h5 class="post-title"><a href="#">Working on new awesome themes for everyone!</a></h5>
                            <div class="post-meta">
                                <span><i class="fa fa-clock-o"></i><a href="#">24.05.2014</a></span>
                                <span><i class="fa fa-comment"></i><a href="#">2 Comentários</a></span>
                            </div>
                            <p class="font-alt">Suspendisse mattis erat et est molestie aliquet consectetur adipiscing elit. Praesent eros justo, convallis non mauris in, varius tincidunt ex. Suspendisse mattis erat et est molestie aliquet.</p>
                            <a href="#" class="btn btn-primary btn-xs">Leia Mais</a>
                        </div>
                    </div>
                    <!-- Post  -->
                    <div class="post post-vertical col-md-6 clearfix">
                        <div class="post-image-thumb">
                            <img src="<?=HOMEP;?>/assets/images/blog/post04-thumb.jpg" alt="" />
                        </div>
                        <div class="post-content">
                            <div class="post-labels">
                                <a href="#" class="label label-primary animated" data-animation="flipInX" data-animation-delay="400">Webdesign</a>
                                <a href="#" class="label label-primary animated" data-animation="flipInX" data-animation-delay="600">Webdevelopment</a>
                            </div>
                            <h5 class="post-title"><a href="#">Working on new awesome themes for everyone!</a></h5>
                            <div class="post-meta">
                                <span><i class="fa fa-clock-o"></i><a href="#">24.05.2014</a></span>
                                <span><i class="fa fa-comment"></i><a href="#">2 Comentários</a></span>
                            </div>
                            <p class="font-alt">Suspendisse mattis erat et est molestie aliquet consectetur adipiscing elit. Praesent eros justo, convallis non mauris in, varius tincidunt ex. Suspendisse mattis erat et est molestie aliquet.</p>
                            <a href="#" class="btn btn-primary btn-xs">Leia Mais</a>
                        </div>
                    </div>
                </div>

                <!-- Pagination -->
                <div class="text-right">
                    <ul class="pagination">
                        <li><a href="#"><span aria-hidden="true"><i class="fa fa-angle-left"></i></span><span class="sr-only">Previous</span></a></li>
                        <li class="active"><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#"><span aria-hidden="true"><i class="fa fa-angle-right"></i></span><span class="sr-only">Next</span></a></li>
                    </ul>
                </div>

            </div>

            <?php include_once('sidebar.phtml');?>

        </div>
    </div>

    <section class="section padded-vertical-70">
        <div class="bg-image bg-image-4"></div>
        <div class="overlay overlay-white editable-alpha" data-alpha="10"></div>
        <div class="container">
            <span class="pull-left icon icon-lg margin-bottom-0 animated" data-animation="bounceIn" data-animation-delay="400"><i class="fa fa-play-circle-o text-primary"></i></span>
            <div class="left-space-lg animated" data-animation="fadeInRight" data-animation-delay="400">
                <h4 class="text-uppercase margin-bottom-0"><strong>Tenha acesso</strong> a aulas exclusivas</h4>
                <p class="lead text-muted font-alt">Cadastre-se e prepare-se para se tornar um desenvolvedor de ponta!</p>
                <a href="#" class="btn btn-primary btn-filled">Quero Acesso!</a><a href="#" class="btn btn-link">Saiba Mais</a>
            </div>
        </div>
    </section>
    <?php


    ?>
</div>
<!-- Content / End -->