<!-- Title Bar -->
<div id="page-title">

    <!-- Breadcrumbs -->
    <div class="bg-grey">
        <div class="container">
            <ol class="breadcrumb text-uppercase">
                <li><a href="#">Home</a></li>
                <li class="active">Working on new awesome themes for everyone!</li>
            </ol>
        </div>
    </div>

</div>
<!-- Title Bar / End -->


<!-- Content -->
<div id="content">

    <div class="container">
        <div class="row padded-top-40">

            <!-- Left Column -->
            <div class="col-md-8">

                <!-- Post  -->
                <article class="post">
                    <div class="post-image margin-bottom-30">
                        <img src="images/blog/post05.jpg" alt="" />
                    </div>
                    <div class="post-labels">
                        <a href="#" class="label label-primary animated" data-animation="flipInX" data-animation-delay="400">Webdesign</a>
                        <a href="#" class="label label-primary animated" data-animation="flipInX" data-animation-delay="600">Webdevelopment</a>
                    </div>
                    <h2 class="post-title">Working on new awesome themes for everyone!</h2>
                    <div class="post-meta">
                        <span><i class="fa fa-clock-o"></i><a href="#">24.05.2014</a></span>
                        <span><i class="fa fa-comment"></i><a href="#">2 Comments</a></span>
                    </div>
                    <p class="lead font-alt">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi pretium enim lacus, eu fermentum velit sagittis eget. Quisque finibus magna in scelerisque dapibus. In finibus sem eget vestibulum tincidunt. Quisque varius turpis luctus augue accumsan egestas.</p>
                    <h5>Introduction</h5>
                    <img src="images/gallery/about01.jpg" class="img-rounded margin-right-20 margin-bottom-20 pull-left" alt="" />
                    <p class="lead">Morbi pretium enim lacus, eu fermentum velit sagittis eget. Quisque finibus magna in scelerisque dapibus. In finibus sem eget vestibulum tincidunt. Quisque varius turpis luctus augue accumsan egestas.</p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tristique suscipit volutpat. Suspendisse iaculis iaculis enim. Integer mattis lorem ut tincidunt egestas. Donec eu lorem et libero semper mollis non id nibh. Duis non nunc sit amet nulla dictum mollis in vitae quam. Sed vitae erat eu massa interdum dignissim. Sed egestas eu eros non dapibus. In libero libero, tempus in semper et, vehicula in lacus. Suspendisse pharetra, dui quis pellentesque tincidunt, diam tortor maximus urna, quis tempor quam eros at metus. Proin commodo sem sed scelerisque scelerisque. Pellentesque felis ligula, blandit et cursus non, blandit at turpis.</p>
                    <h5>Main Part</h5>
                    <img src="images/gallery/about02.jpg" class="img-rounded margin-left-20 margin-bottom-20 pull-right" alt="" />
                    <p class="lead">Morbi pretium enim lacus, eu fermentum velit sagittis eget. Quisque finibus magna in scelerisque dapibus. In finibus sem eget vestibulum tincidunt. Quisque varius turpis luctus augue accumsan egestas.</p>
                    <p> Donec eu lorem et libero semper mollis non id nibh. Duis non nunc sit amet nulla dictum mollis in vitae quam. Sed vitae erat eu massa interdum dignissim. Sed egestas eu eros non dapibus. In libero libero, tempus in semper et, vehicula in lacus. Suspendisse pharetra, dui quis pellentesque tincidunt, diam tortor maximus urna, quis tempor quam eros at metus. Proin commodo sem sed scelerisque scelerisque. Pellentesque felis ligula, blandit et cursus non, blandit at turpis. </p>
                    <!-- Testimonial -->
                    <div class="testimonial margin-bottom-30">
                        <div class="testimonial-content bg-grey font-alt">
                            Sed volutpat purus non odio maximus, eget ultrices mauris rutrum. Phasellus non diam in neque interdum gravida.
                        </div>
                        <div class="testimonial-author testimonial-with-photo">
                            <div class="testimonial-photo"><img class="img-circle" src="images/avatars/avatar01.jpg" alt="" /></div>
                            <div class="testimonial-author-txt text-uppercase">
                                <span class="author-name">Jessica Mary Doe</span>
                                <span class="text-muted text-xs">Google Inc.</span>
                            </div>
                        </div>
                    </div>
                    <h5>Summary</h5>
                    <p class="lead"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tristique suscipit volutpat. Suspendisse iaculis iaculis enim. Integer mattis lorem ut tincidunt egestas. Donec eu lorem et libero semper mollis non id nibh.</p>
                    <ul class="text-primary">
                        <li>Lorem ipsum dolor sit amet</li>
                        <li>Consectetur adipiscing elit</li>
                        <li>Integer molestie lorem at massa
                            <ul>
                                <li>Phasellus iaculis neque</li>
                                <li>Purus sodales ultricies</li>
                                <li>Vestibulum laoreet porttitor sem</li>
                            </ul>
                        </li>
                        <li>Faucibus porta lacus fringilla vel</li>
                        <li>Aenean sit amet erat nunc</li>
                    </ul>
                    <p>Duis non nunc sit amet nulla dictum mollis in vitae quam. Sed vitae erat eu massa interdum dignissim. Sed egestas eu eros non dapibus. In libero libero, tempus in semper et, vehicula in lacus. Suspendisse pharetra, dui quis pellentesque tincidunt, diam tortor maximus urna, quis tempor quam eros at metus. Proin commodo sem sed scelerisque scelerisque. Pellentesque felis ligula, blandit et cursus non, blandit at turpis.</p>
                </article>

                <hr />

                <!-- Author -->
                <h4>About the <strong>author</strong></h4>
                <div class="post-author">
                    <div class="post-author-photo"><img src="images/avatars/avatar01.jpg" alt="" class="img-circle" /></div>
                    <div class="post-author-content">
                        <h5 class="margin-bottom-5">Jessica Webber</h5>
                        <p class="font-alt margin-bottom-10">In libero libero, tempus in semper et, vehicula in lacus. Suspendisse pharetra, dui quis pellentesque tincidunt, diam tortor maximus urna, quis tempor quam eros at metus.</p>
                        <a href="#" class="icon icon-circle icon-filled icon-xs icon-facebook"><i class="fa fa-facebook"></i></a>
                        <a href="#" class="icon icon-circle icon-filled icon-xs icon-twitter"><i class="fa fa-twitter"></i></a>
                        <a href="#" class="icon icon-circle icon-filled icon-xs icon-google-plus"><i class="fa fa-google-plus"></i></a>
                    </div>
                </div>

                <hr />

                <!-- Comments -->
                <h4><strong>Comments</strong> (3)</h4>
                <!-- Comments -->
                <ul class="comments">
                    <li class="single-comment">
                        <div class="comment-avatar"><img src="images/avatars/avatar01.jpg" alt="" /></div>
                        <div class="comment-content">
                            <div class="comment-head">
                                <h5 class="comment-title margin-bottom-0">Really awesome theme!</h5>
                                <span class="text-xs"><span class="text-muted">Added</span> 5 days ago <span class="text-muted">by</span> <a href="#">Michael Kors</a></span>
                            </div>
                            <div class="comment-text font-alt">
                                In ut risus at risus ultricies sodales. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum porttitor congue accumsan. Cum sociis natoque penatibus et magnis dis parturient montes
                            </div>
                            <a href="#" class="btn btn-xs btn-primary"><i class="icon-before fa fa-pencil"></i>Write a reply</a>
                        </div>
                        <ul class="comments">
                            <li class="single-comment">
                                <div class="comment-avatar"><img src="images/avatar-default.jpg" alt="" /></div>
                                <div class="comment-content">
                                    <div class="comment-head">
                                        <h5 class="comment-title margin-bottom-0">Yes, you are right!</h5>
                                        <span class="text-xs"><span class="text-muted">Added</span> 5 days ago <span class="text-muted">by</span> <a href="#">Michael Kors</a></span>
                                    </div>
                                    <div class="comment-text font-alt">
                                        Vestibulum porttitor congue accumsan. Cum sociis natoque penatibus et magnis dis parturient montes
                                    </div>
                                </div>
                            </li>
                            <li class="single-comment">
                                <div class="comment-avatar"><img src="images/avatars/avatar02.jpg" alt="" /></div>
                                <div class="comment-content">
                                    <div class="comment-head">
                                        <h5 class="comment-title margin-bottom-0">Yep!</h5>
                                        <span class="text-xs"><span class="text-muted">Added</span> 5 days ago <span class="text-muted">by</span> <a href="#">Michael Kors</a></span>
                                    </div>
                                    <div class="comment-text font-alt">
                                        Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum porttitor congue accumsan. Cum sociis natoque penatibus et magnis dis parturient montes
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li class="single-comment">
                        <div class="comment-avatar"><img src="images/avatar-default.jpg" alt="" /></div>
                        <div class="comment-content">
                            <div class="comment-head">
                                <h5 class="comment-title margin-bottom-0">Lots of good wishes!</h5>
                                <span class="text-xs"><span class="text-muted">Added</span> 5 days ago <span class="text-muted">by</span> <a href="#">Michael Kors</a></span>
                            </div>
                            <div class="comment-text font-alt">
                                In ut risus at risus ultricies sodales. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum porttitor congue accumsan. Cum sociis natoque penatibus et magnis dis parturient montes
                            </div>
                            <a href="#" class="btn btn-xs btn-primary"><i class="icon-before fa fa-pencil"></i>Write a reply</a>
                        </div>
                    </li>
                    <li class="single-comment">
                        <div class="comment-avatar"><img src="images/avatars/avatar01.jpg" alt="" /></div>
                        <div class="comment-content">
                            <div class="comment-head">
                                <h5 class="comment-title margin-bottom-0">Really awesome theme!</h5>
                                <span class="text-xs"><span class="text-muted">Added</span> 5 days ago <span class="text-muted">by</span> <a href="#">Michael Kors</a></span>
                            </div>
                            <div class="comment-text font-alt">
                                In ut risus at risus ultricies sodales.  Vestibulum porttitor congue accumsan. Cum sociis natoque penatibus et magnis dis parturient montes
                            </div>
                            <a href="#" class="btn btn-xs btn-primary"><i class="icon-before fa fa-pencil"></i>Write a reply</a>
                        </div>
                    </li>
                </ul>

                <hr />

                <!-- Write a comment -->
                <h4><strong>Write</strong> a comment</h4>
                <form class="margin-bottom-40 clearfix">
                    <div class="form-group">
                        <input type="text" class="form-control" id="commentName" name="name" placeholder="Name">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" id="comment" name="message" rows="3"  placeholder="Message"></textarea>
                    </div>
                    <div class="form-group clearfix">
                        <button type="submit" class="btn btn-primary btn-filled btn-sm pull-right">Send it!</button>
                    </div>
                </form>

            </div>

            <!-- Right Column -->
            <?php include_once('sidebar.phtml');?>

        </div>
    </div>