<?php
$users = $this->view->usuarios;
foreach($users as $user);
?>
<section class="content">
    <section class="widget">
        <header>
            <span class="icon">&#128101;</span>
            <hgroup>
                <h1>Perfil</h1>
                <h2>Meu perfil</h2>
            </hgroup>
        </header>

        <div class="content">
            <form name="formulario" action="" method="post" enctype="multipart/form-data" _lpchecked="1">
                <div class="field-wrap">
                    <p>Nome:</p>
                    <input type="text" name="nome" value="<?php echo $user['nome'];?>" placeholder="">
                </div>

                <div class="field-wrap">
                    <p>E-mail:</p>
                    <input type="text" disabled style="color:#e1e1e1;" name="email" value="<?php echo $user['email'];?>" placeholder="">
                </div>

                <div class="field-wrap">
                    <p>Senha:</p>
                    <input type="password" name="senha" value="<?php echo $user['senha'];?>" placeholder="" >
                </div>

                    <?php

                        if($user['tipo'] == 1 ){
                            $tipo = "Administrador";
                        }else if($user['tipo'] == 2){
                            $tipo = "Atendente";
                            echo '<input type="hidden" name="tipo" value="2" /> ';
                        }

                        if($_SESSION['nivel'] == 1){
                      ?>
                    <div class="field-wrap">
                        <p>Nível</p>
                        <select name="tipo">

                            <option selected="selected" value="<?php echo $user['tipo'] ?>"><?php echo $tipo ?> &nbsp;&nbsp;</option>
                            <option disabled>================</option>
                            <option value="1">Administrador &nbsp;&nbsp;</option>
                            <option value="2">Atendente &nbsp;&nbsp;</option>
                        </select>
                    </div>

                        <div class="field-wrap">
                            <?php

                            if($user['status'] == 1){
                                $status = "Ativo";
                            }else if($user['status'] == 0){
                                $status = "Inativo";
                            }

                            ?>
                            <p>Status</p>
                            <select name="status">
                            <option selected="selected" value="<?php echo $user['status'] ?>"><?php echo $status; ?></option>
                            <option disabled>================</option>
                            <option  value="1">Ativo</option>
                            <option value="0">Inativo</option>
                            </select>
                        </div>
                    <?php
                }
            ?>
                        <br>

                        <button type="submit" name="sendForm" class="green">Atualizar</button> <button type="reset" class="">Limpar</button>

                        </div>
                    </div>
                </form>
            </div>
    </section>
</section>