<?php
$users = $this->view->usuarios;
foreach($users as $user);

if($user['tipo'] == 1 ){
    $tipo = "Administrador";
}else if($user['tipo'] == 2){
    $tipo = "Atendente";
    header("Location: dashboard");
}

?>
<section class="content">
    <section class="widget">
        <header>
            <span class="icon">&#128101;</span>
            <hgroup>
                <h1>Usuários</h1>
                <h2>Gestão de Usuários</h2>
            </hgroup>
        </header>

            <div class="content">
                <table id="myTable" border="0" width="100">
                    <thead>
                    <tr>
                        <th class="header">E-mail</th>
                        <th class="header">Nível</th>
                        <th class="header">Status</th>
                        <th colspan="3" class="header">Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr class="odd">


                        <?php
                        if($user['status'] == 1 ){
                            $status = "Ativo";
                        }else if($user['tipo'] == 0){
                            $status = "Inativo";
                        }
                        ?>

                        <td><?php echo $user['email'];?></td>
                        <td><?php echo $tipo;?></td>
                        <td><?php echo $status;?></td>
                        <td><a href="/admin/profile"><span class="button green">Editar</span></a></td>
                        <td><a href="/admin/profile"><span class="button red">Desativar</span></a></td>
                        <td></td>
                    </tr>

                    </tbody>
                </table>
            </div>

    </section>
</section>